// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct BiomeNoise {
 *     DoublePerlinNoise climate[6];
 *     PerlinNoise oct[46];
 *     Spline* sp;
 *     SplineStack ss;
 *     int nptype;
 *     int mc;
 * };
 * }
 */
public class BiomeNoise {

    public static MemoryLayout $LAYOUT() {
        return constants$27.const$5;
    }
    public static MemorySegment climate(MemorySegment seg) {
        return seg.asSlice(0, 240);
    }
    public static MemorySegment oct(MemorySegment seg) {
        return seg.asSlice(240, 14720);
    }
    public static VarHandle sp$VH() {
        return constants$28.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Spline* sp;
     * }
     */
    public static MemorySegment sp(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$28.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Spline* sp;
     * }
     */
    public static void sp(MemorySegment seg, MemorySegment x) {
        constants$28.const$0.set(seg, x);
    }
    public static MemorySegment spAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$28.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void spAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$28.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment ss(MemorySegment seg) {
        return seg.asSlice(14968, 9616);
    }
    public static VarHandle nptype$VH() {
        return constants$28.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int nptype;
     * }
     */
    public static int nptype(MemorySegment seg) {
        return (int)constants$28.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int nptype;
     * }
     */
    public static void nptype(MemorySegment seg, int x) {
        constants$28.const$1.set(seg, x);
    }
    public static int nptypeAtIndex(MemorySegment seg, long index) {
        return (int)constants$28.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void nptypeAtIndex(MemorySegment seg, long index, int x) {
        constants$28.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mc$VH() {
        return constants$28.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static int mc(MemorySegment seg) {
        return (int)constants$28.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static void mc(MemorySegment seg, int x) {
        constants$28.const$2.set(seg, x);
    }
    public static int mcAtIndex(MemorySegment seg, long index) {
        return (int)constants$28.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void mcAtIndex(MemorySegment seg, long index, int x) {
        constants$28.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}