// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct BiomeFilter {
 *     uint64_t tempsToFind;
 *     uint64_t otempToFind;
 *     uint64_t majorToFind;
 *     uint64_t edgesToFind;
 *     uint64_t raresToFind;
 *     uint64_t raresToFindM;
 *     uint64_t shoreToFind;
 *     uint64_t shoreToFindM;
 *     uint64_t riverToFind;
 *     uint64_t riverToFindM;
 *     uint64_t oceanToFind;
 *     int specialCnt;
 *     uint32_t flags;
 *     uint64_t tempsToExcl;
 *     uint64_t majorToExcl;
 *     uint64_t edgesToExcl;
 *     uint64_t raresToExcl;
 *     uint64_t raresToExclM;
 *     uint64_t shoreToExcl;
 *     uint64_t shoreToExclM;
 *     uint64_t riverToExcl;
 *     uint64_t riverToExclM;
 *     uint64_t biomeToExcl;
 *     uint64_t biomeToExclM;
 *     uint64_t biomeToFind;
 *     uint64_t biomeToFindM;
 *     uint64_t biomeToPick;
 *     uint64_t biomeToPickM;
 * };
 * }
 */
public class BiomeFilter {

    public static MemoryLayout $LAYOUT() {
        return constants$59.const$2;
    }
    public static VarHandle tempsToFind$VH() {
        return constants$59.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t tempsToFind;
     * }
     */
    public static long tempsToFind(MemorySegment seg) {
        return (long)constants$59.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t tempsToFind;
     * }
     */
    public static void tempsToFind(MemorySegment seg, long x) {
        constants$59.const$3.set(seg, x);
    }
    public static long tempsToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$59.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void tempsToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$59.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle otempToFind$VH() {
        return constants$59.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t otempToFind;
     * }
     */
    public static long otempToFind(MemorySegment seg) {
        return (long)constants$59.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t otempToFind;
     * }
     */
    public static void otempToFind(MemorySegment seg, long x) {
        constants$59.const$4.set(seg, x);
    }
    public static long otempToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$59.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void otempToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$59.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle majorToFind$VH() {
        return constants$59.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t majorToFind;
     * }
     */
    public static long majorToFind(MemorySegment seg) {
        return (long)constants$59.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t majorToFind;
     * }
     */
    public static void majorToFind(MemorySegment seg, long x) {
        constants$59.const$5.set(seg, x);
    }
    public static long majorToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$59.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void majorToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$59.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle edgesToFind$VH() {
        return constants$60.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t edgesToFind;
     * }
     */
    public static long edgesToFind(MemorySegment seg) {
        return (long)constants$60.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t edgesToFind;
     * }
     */
    public static void edgesToFind(MemorySegment seg, long x) {
        constants$60.const$0.set(seg, x);
    }
    public static long edgesToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$60.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void edgesToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$60.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle raresToFind$VH() {
        return constants$60.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t raresToFind;
     * }
     */
    public static long raresToFind(MemorySegment seg) {
        return (long)constants$60.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t raresToFind;
     * }
     */
    public static void raresToFind(MemorySegment seg, long x) {
        constants$60.const$1.set(seg, x);
    }
    public static long raresToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$60.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void raresToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$60.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle raresToFindM$VH() {
        return constants$60.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t raresToFindM;
     * }
     */
    public static long raresToFindM(MemorySegment seg) {
        return (long)constants$60.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t raresToFindM;
     * }
     */
    public static void raresToFindM(MemorySegment seg, long x) {
        constants$60.const$2.set(seg, x);
    }
    public static long raresToFindMAtIndex(MemorySegment seg, long index) {
        return (long)constants$60.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void raresToFindMAtIndex(MemorySegment seg, long index, long x) {
        constants$60.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shoreToFind$VH() {
        return constants$60.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t shoreToFind;
     * }
     */
    public static long shoreToFind(MemorySegment seg) {
        return (long)constants$60.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t shoreToFind;
     * }
     */
    public static void shoreToFind(MemorySegment seg, long x) {
        constants$60.const$3.set(seg, x);
    }
    public static long shoreToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$60.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void shoreToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$60.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shoreToFindM$VH() {
        return constants$60.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t shoreToFindM;
     * }
     */
    public static long shoreToFindM(MemorySegment seg) {
        return (long)constants$60.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t shoreToFindM;
     * }
     */
    public static void shoreToFindM(MemorySegment seg, long x) {
        constants$60.const$4.set(seg, x);
    }
    public static long shoreToFindMAtIndex(MemorySegment seg, long index) {
        return (long)constants$60.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void shoreToFindMAtIndex(MemorySegment seg, long index, long x) {
        constants$60.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle riverToFind$VH() {
        return constants$60.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t riverToFind;
     * }
     */
    public static long riverToFind(MemorySegment seg) {
        return (long)constants$60.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t riverToFind;
     * }
     */
    public static void riverToFind(MemorySegment seg, long x) {
        constants$60.const$5.set(seg, x);
    }
    public static long riverToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$60.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void riverToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$60.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle riverToFindM$VH() {
        return constants$61.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t riverToFindM;
     * }
     */
    public static long riverToFindM(MemorySegment seg) {
        return (long)constants$61.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t riverToFindM;
     * }
     */
    public static void riverToFindM(MemorySegment seg, long x) {
        constants$61.const$0.set(seg, x);
    }
    public static long riverToFindMAtIndex(MemorySegment seg, long index) {
        return (long)constants$61.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void riverToFindMAtIndex(MemorySegment seg, long index, long x) {
        constants$61.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle oceanToFind$VH() {
        return constants$61.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t oceanToFind;
     * }
     */
    public static long oceanToFind(MemorySegment seg) {
        return (long)constants$61.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t oceanToFind;
     * }
     */
    public static void oceanToFind(MemorySegment seg, long x) {
        constants$61.const$1.set(seg, x);
    }
    public static long oceanToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$61.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void oceanToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$61.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle specialCnt$VH() {
        return constants$61.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int specialCnt;
     * }
     */
    public static int specialCnt(MemorySegment seg) {
        return (int)constants$61.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int specialCnt;
     * }
     */
    public static void specialCnt(MemorySegment seg, int x) {
        constants$61.const$2.set(seg, x);
    }
    public static int specialCntAtIndex(MemorySegment seg, long index) {
        return (int)constants$61.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void specialCntAtIndex(MemorySegment seg, long index, int x) {
        constants$61.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle flags$VH() {
        return constants$61.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t flags;
     * }
     */
    public static int flags(MemorySegment seg) {
        return (int)constants$61.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t flags;
     * }
     */
    public static void flags(MemorySegment seg, int x) {
        constants$61.const$3.set(seg, x);
    }
    public static int flagsAtIndex(MemorySegment seg, long index) {
        return (int)constants$61.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void flagsAtIndex(MemorySegment seg, long index, int x) {
        constants$61.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle tempsToExcl$VH() {
        return constants$61.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t tempsToExcl;
     * }
     */
    public static long tempsToExcl(MemorySegment seg) {
        return (long)constants$61.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t tempsToExcl;
     * }
     */
    public static void tempsToExcl(MemorySegment seg, long x) {
        constants$61.const$4.set(seg, x);
    }
    public static long tempsToExclAtIndex(MemorySegment seg, long index) {
        return (long)constants$61.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void tempsToExclAtIndex(MemorySegment seg, long index, long x) {
        constants$61.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle majorToExcl$VH() {
        return constants$61.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t majorToExcl;
     * }
     */
    public static long majorToExcl(MemorySegment seg) {
        return (long)constants$61.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t majorToExcl;
     * }
     */
    public static void majorToExcl(MemorySegment seg, long x) {
        constants$61.const$5.set(seg, x);
    }
    public static long majorToExclAtIndex(MemorySegment seg, long index) {
        return (long)constants$61.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void majorToExclAtIndex(MemorySegment seg, long index, long x) {
        constants$61.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle edgesToExcl$VH() {
        return constants$62.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t edgesToExcl;
     * }
     */
    public static long edgesToExcl(MemorySegment seg) {
        return (long)constants$62.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t edgesToExcl;
     * }
     */
    public static void edgesToExcl(MemorySegment seg, long x) {
        constants$62.const$0.set(seg, x);
    }
    public static long edgesToExclAtIndex(MemorySegment seg, long index) {
        return (long)constants$62.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void edgesToExclAtIndex(MemorySegment seg, long index, long x) {
        constants$62.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle raresToExcl$VH() {
        return constants$62.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t raresToExcl;
     * }
     */
    public static long raresToExcl(MemorySegment seg) {
        return (long)constants$62.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t raresToExcl;
     * }
     */
    public static void raresToExcl(MemorySegment seg, long x) {
        constants$62.const$1.set(seg, x);
    }
    public static long raresToExclAtIndex(MemorySegment seg, long index) {
        return (long)constants$62.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void raresToExclAtIndex(MemorySegment seg, long index, long x) {
        constants$62.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle raresToExclM$VH() {
        return constants$62.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t raresToExclM;
     * }
     */
    public static long raresToExclM(MemorySegment seg) {
        return (long)constants$62.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t raresToExclM;
     * }
     */
    public static void raresToExclM(MemorySegment seg, long x) {
        constants$62.const$2.set(seg, x);
    }
    public static long raresToExclMAtIndex(MemorySegment seg, long index) {
        return (long)constants$62.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void raresToExclMAtIndex(MemorySegment seg, long index, long x) {
        constants$62.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shoreToExcl$VH() {
        return constants$62.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t shoreToExcl;
     * }
     */
    public static long shoreToExcl(MemorySegment seg) {
        return (long)constants$62.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t shoreToExcl;
     * }
     */
    public static void shoreToExcl(MemorySegment seg, long x) {
        constants$62.const$3.set(seg, x);
    }
    public static long shoreToExclAtIndex(MemorySegment seg, long index) {
        return (long)constants$62.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void shoreToExclAtIndex(MemorySegment seg, long index, long x) {
        constants$62.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shoreToExclM$VH() {
        return constants$62.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t shoreToExclM;
     * }
     */
    public static long shoreToExclM(MemorySegment seg) {
        return (long)constants$62.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t shoreToExclM;
     * }
     */
    public static void shoreToExclM(MemorySegment seg, long x) {
        constants$62.const$4.set(seg, x);
    }
    public static long shoreToExclMAtIndex(MemorySegment seg, long index) {
        return (long)constants$62.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void shoreToExclMAtIndex(MemorySegment seg, long index, long x) {
        constants$62.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle riverToExcl$VH() {
        return constants$62.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t riverToExcl;
     * }
     */
    public static long riverToExcl(MemorySegment seg) {
        return (long)constants$62.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t riverToExcl;
     * }
     */
    public static void riverToExcl(MemorySegment seg, long x) {
        constants$62.const$5.set(seg, x);
    }
    public static long riverToExclAtIndex(MemorySegment seg, long index) {
        return (long)constants$62.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void riverToExclAtIndex(MemorySegment seg, long index, long x) {
        constants$62.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle riverToExclM$VH() {
        return constants$63.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t riverToExclM;
     * }
     */
    public static long riverToExclM(MemorySegment seg) {
        return (long)constants$63.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t riverToExclM;
     * }
     */
    public static void riverToExclM(MemorySegment seg, long x) {
        constants$63.const$0.set(seg, x);
    }
    public static long riverToExclMAtIndex(MemorySegment seg, long index) {
        return (long)constants$63.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void riverToExclMAtIndex(MemorySegment seg, long index, long x) {
        constants$63.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle biomeToExcl$VH() {
        return constants$63.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t biomeToExcl;
     * }
     */
    public static long biomeToExcl(MemorySegment seg) {
        return (long)constants$63.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t biomeToExcl;
     * }
     */
    public static void biomeToExcl(MemorySegment seg, long x) {
        constants$63.const$1.set(seg, x);
    }
    public static long biomeToExclAtIndex(MemorySegment seg, long index) {
        return (long)constants$63.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void biomeToExclAtIndex(MemorySegment seg, long index, long x) {
        constants$63.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle biomeToExclM$VH() {
        return constants$63.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t biomeToExclM;
     * }
     */
    public static long biomeToExclM(MemorySegment seg) {
        return (long)constants$63.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t biomeToExclM;
     * }
     */
    public static void biomeToExclM(MemorySegment seg, long x) {
        constants$63.const$2.set(seg, x);
    }
    public static long biomeToExclMAtIndex(MemorySegment seg, long index) {
        return (long)constants$63.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void biomeToExclMAtIndex(MemorySegment seg, long index, long x) {
        constants$63.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle biomeToFind$VH() {
        return constants$63.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t biomeToFind;
     * }
     */
    public static long biomeToFind(MemorySegment seg) {
        return (long)constants$63.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t biomeToFind;
     * }
     */
    public static void biomeToFind(MemorySegment seg, long x) {
        constants$63.const$3.set(seg, x);
    }
    public static long biomeToFindAtIndex(MemorySegment seg, long index) {
        return (long)constants$63.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void biomeToFindAtIndex(MemorySegment seg, long index, long x) {
        constants$63.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle biomeToFindM$VH() {
        return constants$63.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t biomeToFindM;
     * }
     */
    public static long biomeToFindM(MemorySegment seg) {
        return (long)constants$63.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t biomeToFindM;
     * }
     */
    public static void biomeToFindM(MemorySegment seg, long x) {
        constants$63.const$4.set(seg, x);
    }
    public static long biomeToFindMAtIndex(MemorySegment seg, long index) {
        return (long)constants$63.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void biomeToFindMAtIndex(MemorySegment seg, long index, long x) {
        constants$63.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle biomeToPick$VH() {
        return constants$63.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t biomeToPick;
     * }
     */
    public static long biomeToPick(MemorySegment seg) {
        return (long)constants$63.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t biomeToPick;
     * }
     */
    public static void biomeToPick(MemorySegment seg, long x) {
        constants$63.const$5.set(seg, x);
    }
    public static long biomeToPickAtIndex(MemorySegment seg, long index) {
        return (long)constants$63.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void biomeToPickAtIndex(MemorySegment seg, long index, long x) {
        constants$63.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle biomeToPickM$VH() {
        return constants$64.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t biomeToPickM;
     * }
     */
    public static long biomeToPickM(MemorySegment seg) {
        return (long)constants$64.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t biomeToPickM;
     * }
     */
    public static void biomeToPickM(MemorySegment seg, long x) {
        constants$64.const$0.set(seg, x);
    }
    public static long biomeToPickMAtIndex(MemorySegment seg, long index) {
        return (long)constants$64.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void biomeToPickMAtIndex(MemorySegment seg, long index, long x) {
        constants$64.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}