// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct BiomeTree {
 *     const uint32_t* steps;
 *     const int32_t* param;
 *     const uint64_t* nodes;
 *     uint32_t order;
 *     uint32_t len;
 * };
 * }
 */
public class BiomeTree {

    public static MemoryLayout $LAYOUT() {
        return constants$29.const$0;
    }
    public static VarHandle steps$VH() {
        return constants$29.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const uint32_t* steps;
     * }
     */
    public static MemorySegment steps(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$29.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const uint32_t* steps;
     * }
     */
    public static void steps(MemorySegment seg, MemorySegment x) {
        constants$29.const$1.set(seg, x);
    }
    public static MemorySegment stepsAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$29.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void stepsAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$29.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle param$VH() {
        return constants$29.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const int32_t* param;
     * }
     */
    public static MemorySegment param(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$29.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const int32_t* param;
     * }
     */
    public static void param(MemorySegment seg, MemorySegment x) {
        constants$29.const$2.set(seg, x);
    }
    public static MemorySegment paramAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$29.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void paramAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$29.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle nodes$VH() {
        return constants$29.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const uint64_t* nodes;
     * }
     */
    public static MemorySegment nodes(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$29.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const uint64_t* nodes;
     * }
     */
    public static void nodes(MemorySegment seg, MemorySegment x) {
        constants$29.const$3.set(seg, x);
    }
    public static MemorySegment nodesAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$29.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void nodesAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$29.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle order$VH() {
        return constants$29.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t order;
     * }
     */
    public static int order(MemorySegment seg) {
        return (int)constants$29.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t order;
     * }
     */
    public static void order(MemorySegment seg, int x) {
        constants$29.const$4.set(seg, x);
    }
    public static int orderAtIndex(MemorySegment seg, long index) {
        return (int)constants$29.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void orderAtIndex(MemorySegment seg, long index, int x) {
        constants$29.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle len$VH() {
        return constants$29.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t len;
     * }
     */
    public static int len(MemorySegment seg) {
        return (int)constants$29.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t len;
     * }
     */
    public static void len(MemorySegment seg, int x) {
        constants$29.const$5.set(seg, x);
    }
    public static int lenAtIndex(MemorySegment seg, long index) {
        return (int)constants$29.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void lenAtIndex(MemorySegment seg, long index, int x) {
        constants$29.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}