// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct CanyonCarverConfig {
 *     int dim;
 *     float probability;
 *     int carverIndex;
 *     int range;
 *     int (*y)(uint64_t*,int,int,int);
 *     int minY;
 *     int maxY;
 *     int innerY;
 *     float yScale;
 *     float (*verticalRotation)(uint64_t*,float,float);
 *     float minVerRot;
 *     float maxVerRot;
 *     float (*distanceFactor)(uint64_t*,float,float);
 *     float minDistance;
 *     float maxDistance;
 *     float (*thickness)(uint64_t*,float,float,float);
 *     float minThickness;
 *     float maxThickness;
 *     float plateauThickness;
 *     int widthSmoothness;
 *     float (*horizontalRadiusFactor)(uint64_t*,float,float);
 *     float minHorRadius;
 *     float maxHorRadius;
 *     float verticalRadiusDefaultFactor;
 *     float verticalRadiusCenterFactor;
 * };
 * }
 */
public class CanyonCarverConfig {

    public static MemoryLayout $LAYOUT() {
        return constants$74.const$3;
    }
    public static VarHandle dim$VH() {
        return constants$74.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int dim;
     * }
     */
    public static int dim(MemorySegment seg) {
        return (int)constants$74.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int dim;
     * }
     */
    public static void dim(MemorySegment seg, int x) {
        constants$74.const$4.set(seg, x);
    }
    public static int dimAtIndex(MemorySegment seg, long index) {
        return (int)constants$74.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void dimAtIndex(MemorySegment seg, long index, int x) {
        constants$74.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle probability$VH() {
        return constants$74.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float probability;
     * }
     */
    public static float probability(MemorySegment seg) {
        return (float)constants$74.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float probability;
     * }
     */
    public static void probability(MemorySegment seg, float x) {
        constants$74.const$5.set(seg, x);
    }
    public static float probabilityAtIndex(MemorySegment seg, long index) {
        return (float)constants$74.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void probabilityAtIndex(MemorySegment seg, long index, float x) {
        constants$74.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle carverIndex$VH() {
        return constants$75.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int carverIndex;
     * }
     */
    public static int carverIndex(MemorySegment seg) {
        return (int)constants$75.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int carverIndex;
     * }
     */
    public static void carverIndex(MemorySegment seg, int x) {
        constants$75.const$0.set(seg, x);
    }
    public static int carverIndexAtIndex(MemorySegment seg, long index) {
        return (int)constants$75.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void carverIndexAtIndex(MemorySegment seg, long index, int x) {
        constants$75.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle range$VH() {
        return constants$75.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int range;
     * }
     */
    public static int range(MemorySegment seg) {
        return (int)constants$75.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int range;
     * }
     */
    public static void range(MemorySegment seg, int x) {
        constants$75.const$1.set(seg, x);
    }
    public static int rangeAtIndex(MemorySegment seg, long index) {
        return (int)constants$75.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void rangeAtIndex(MemorySegment seg, long index, int x) {
        constants$75.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * int (*y)(uint64_t*,int,int,int);
     * }
     */
    public interface y {

        int apply(java.lang.foreign.MemorySegment _x0, int _x1, int _x2, int _x3);
        static MemorySegment allocate(y fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$75.const$2, fi, constants$71.const$1, scope);
        }
        static y ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, int __x1, int __x2, int __x3) -> {
                try {
                    return (int)constants$75.const$3.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle y$VH() {
        return constants$75.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*y)(uint64_t*,int,int,int);
     * }
     */
    public static MemorySegment y(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$75.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*y)(uint64_t*,int,int,int);
     * }
     */
    public static void y(MemorySegment seg, MemorySegment x) {
        constants$75.const$4.set(seg, x);
    }
    public static MemorySegment yAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$75.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void yAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$75.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static y y(MemorySegment segment, Arena scope) {
        return y.ofAddress(y(segment), scope);
    }
    public static VarHandle minY$VH() {
        return constants$75.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int minY;
     * }
     */
    public static int minY(MemorySegment seg) {
        return (int)constants$75.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int minY;
     * }
     */
    public static void minY(MemorySegment seg, int x) {
        constants$75.const$5.set(seg, x);
    }
    public static int minYAtIndex(MemorySegment seg, long index) {
        return (int)constants$75.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void minYAtIndex(MemorySegment seg, long index, int x) {
        constants$75.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxY$VH() {
        return constants$76.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int maxY;
     * }
     */
    public static int maxY(MemorySegment seg) {
        return (int)constants$76.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int maxY;
     * }
     */
    public static void maxY(MemorySegment seg, int x) {
        constants$76.const$0.set(seg, x);
    }
    public static int maxYAtIndex(MemorySegment seg, long index) {
        return (int)constants$76.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void maxYAtIndex(MemorySegment seg, long index, int x) {
        constants$76.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle innerY$VH() {
        return constants$76.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int innerY;
     * }
     */
    public static int innerY(MemorySegment seg) {
        return (int)constants$76.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int innerY;
     * }
     */
    public static void innerY(MemorySegment seg, int x) {
        constants$76.const$1.set(seg, x);
    }
    public static int innerYAtIndex(MemorySegment seg, long index) {
        return (int)constants$76.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void innerYAtIndex(MemorySegment seg, long index, int x) {
        constants$76.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle yScale$VH() {
        return constants$76.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float yScale;
     * }
     */
    public static float yScale(MemorySegment seg) {
        return (float)constants$76.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float yScale;
     * }
     */
    public static void yScale(MemorySegment seg, float x) {
        constants$76.const$2.set(seg, x);
    }
    public static float yScaleAtIndex(MemorySegment seg, long index) {
        return (float)constants$76.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void yScaleAtIndex(MemorySegment seg, long index, float x) {
        constants$76.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*verticalRotation)(uint64_t*,float,float);
     * }
     */
    public interface verticalRotation {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2);
        static MemorySegment allocate(verticalRotation fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$76.const$4, fi, constants$76.const$3, scope);
        }
        static verticalRotation ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2) -> {
                try {
                    return (float)constants$76.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle verticalRotation$VH() {
        return constants$77.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*verticalRotation)(uint64_t*,float,float);
     * }
     */
    public static MemorySegment verticalRotation(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$77.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*verticalRotation)(uint64_t*,float,float);
     * }
     */
    public static void verticalRotation(MemorySegment seg, MemorySegment x) {
        constants$77.const$0.set(seg, x);
    }
    public static MemorySegment verticalRotationAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$77.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void verticalRotationAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$77.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static verticalRotation verticalRotation(MemorySegment segment, Arena scope) {
        return verticalRotation.ofAddress(verticalRotation(segment), scope);
    }
    public static VarHandle minVerRot$VH() {
        return constants$77.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minVerRot;
     * }
     */
    public static float minVerRot(MemorySegment seg) {
        return (float)constants$77.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minVerRot;
     * }
     */
    public static void minVerRot(MemorySegment seg, float x) {
        constants$77.const$1.set(seg, x);
    }
    public static float minVerRotAtIndex(MemorySegment seg, long index) {
        return (float)constants$77.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void minVerRotAtIndex(MemorySegment seg, long index, float x) {
        constants$77.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxVerRot$VH() {
        return constants$77.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxVerRot;
     * }
     */
    public static float maxVerRot(MemorySegment seg) {
        return (float)constants$77.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxVerRot;
     * }
     */
    public static void maxVerRot(MemorySegment seg, float x) {
        constants$77.const$2.set(seg, x);
    }
    public static float maxVerRotAtIndex(MemorySegment seg, long index) {
        return (float)constants$77.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void maxVerRotAtIndex(MemorySegment seg, long index, float x) {
        constants$77.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*distanceFactor)(uint64_t*,float,float);
     * }
     */
    public interface distanceFactor {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2);
        static MemorySegment allocate(distanceFactor fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$77.const$3, fi, constants$76.const$3, scope);
        }
        static distanceFactor ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2) -> {
                try {
                    return (float)constants$76.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle distanceFactor$VH() {
        return constants$77.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*distanceFactor)(uint64_t*,float,float);
     * }
     */
    public static MemorySegment distanceFactor(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$77.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*distanceFactor)(uint64_t*,float,float);
     * }
     */
    public static void distanceFactor(MemorySegment seg, MemorySegment x) {
        constants$77.const$4.set(seg, x);
    }
    public static MemorySegment distanceFactorAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$77.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void distanceFactorAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$77.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static distanceFactor distanceFactor(MemorySegment segment, Arena scope) {
        return distanceFactor.ofAddress(distanceFactor(segment), scope);
    }
    public static VarHandle minDistance$VH() {
        return constants$77.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minDistance;
     * }
     */
    public static float minDistance(MemorySegment seg) {
        return (float)constants$77.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minDistance;
     * }
     */
    public static void minDistance(MemorySegment seg, float x) {
        constants$77.const$5.set(seg, x);
    }
    public static float minDistanceAtIndex(MemorySegment seg, long index) {
        return (float)constants$77.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void minDistanceAtIndex(MemorySegment seg, long index, float x) {
        constants$77.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxDistance$VH() {
        return constants$78.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxDistance;
     * }
     */
    public static float maxDistance(MemorySegment seg) {
        return (float)constants$78.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxDistance;
     * }
     */
    public static void maxDistance(MemorySegment seg, float x) {
        constants$78.const$0.set(seg, x);
    }
    public static float maxDistanceAtIndex(MemorySegment seg, long index) {
        return (float)constants$78.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void maxDistanceAtIndex(MemorySegment seg, long index, float x) {
        constants$78.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*thickness)(uint64_t*,float,float,float);
     * }
     */
    public interface thickness {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2, float _x3);
        static MemorySegment allocate(thickness fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$78.const$2, fi, constants$78.const$1, scope);
        }
        static thickness ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2, float __x3) -> {
                try {
                    return (float)constants$78.const$3.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle thickness$VH() {
        return constants$78.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*thickness)(uint64_t*,float,float,float);
     * }
     */
    public static MemorySegment thickness(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$78.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*thickness)(uint64_t*,float,float,float);
     * }
     */
    public static void thickness(MemorySegment seg, MemorySegment x) {
        constants$78.const$4.set(seg, x);
    }
    public static MemorySegment thicknessAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$78.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void thicknessAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$78.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static thickness thickness(MemorySegment segment, Arena scope) {
        return thickness.ofAddress(thickness(segment), scope);
    }
    public static VarHandle minThickness$VH() {
        return constants$78.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minThickness;
     * }
     */
    public static float minThickness(MemorySegment seg) {
        return (float)constants$78.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minThickness;
     * }
     */
    public static void minThickness(MemorySegment seg, float x) {
        constants$78.const$5.set(seg, x);
    }
    public static float minThicknessAtIndex(MemorySegment seg, long index) {
        return (float)constants$78.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void minThicknessAtIndex(MemorySegment seg, long index, float x) {
        constants$78.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxThickness$VH() {
        return constants$79.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxThickness;
     * }
     */
    public static float maxThickness(MemorySegment seg) {
        return (float)constants$79.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxThickness;
     * }
     */
    public static void maxThickness(MemorySegment seg, float x) {
        constants$79.const$0.set(seg, x);
    }
    public static float maxThicknessAtIndex(MemorySegment seg, long index) {
        return (float)constants$79.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void maxThicknessAtIndex(MemorySegment seg, long index, float x) {
        constants$79.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle plateauThickness$VH() {
        return constants$79.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float plateauThickness;
     * }
     */
    public static float plateauThickness(MemorySegment seg) {
        return (float)constants$79.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float plateauThickness;
     * }
     */
    public static void plateauThickness(MemorySegment seg, float x) {
        constants$79.const$1.set(seg, x);
    }
    public static float plateauThicknessAtIndex(MemorySegment seg, long index) {
        return (float)constants$79.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void plateauThicknessAtIndex(MemorySegment seg, long index, float x) {
        constants$79.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle widthSmoothness$VH() {
        return constants$79.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int widthSmoothness;
     * }
     */
    public static int widthSmoothness(MemorySegment seg) {
        return (int)constants$79.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int widthSmoothness;
     * }
     */
    public static void widthSmoothness(MemorySegment seg, int x) {
        constants$79.const$2.set(seg, x);
    }
    public static int widthSmoothnessAtIndex(MemorySegment seg, long index) {
        return (int)constants$79.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void widthSmoothnessAtIndex(MemorySegment seg, long index, int x) {
        constants$79.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*horizontalRadiusFactor)(uint64_t*,float,float);
     * }
     */
    public interface horizontalRadiusFactor {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2);
        static MemorySegment allocate(horizontalRadiusFactor fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$79.const$3, fi, constants$76.const$3, scope);
        }
        static horizontalRadiusFactor ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2) -> {
                try {
                    return (float)constants$76.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle horizontalRadiusFactor$VH() {
        return constants$79.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*horizontalRadiusFactor)(uint64_t*,float,float);
     * }
     */
    public static MemorySegment horizontalRadiusFactor(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$79.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*horizontalRadiusFactor)(uint64_t*,float,float);
     * }
     */
    public static void horizontalRadiusFactor(MemorySegment seg, MemorySegment x) {
        constants$79.const$4.set(seg, x);
    }
    public static MemorySegment horizontalRadiusFactorAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$79.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void horizontalRadiusFactorAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$79.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static horizontalRadiusFactor horizontalRadiusFactor(MemorySegment segment, Arena scope) {
        return horizontalRadiusFactor.ofAddress(horizontalRadiusFactor(segment), scope);
    }
    public static VarHandle minHorRadius$VH() {
        return constants$79.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minHorRadius;
     * }
     */
    public static float minHorRadius(MemorySegment seg) {
        return (float)constants$79.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minHorRadius;
     * }
     */
    public static void minHorRadius(MemorySegment seg, float x) {
        constants$79.const$5.set(seg, x);
    }
    public static float minHorRadiusAtIndex(MemorySegment seg, long index) {
        return (float)constants$79.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void minHorRadiusAtIndex(MemorySegment seg, long index, float x) {
        constants$79.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxHorRadius$VH() {
        return constants$80.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxHorRadius;
     * }
     */
    public static float maxHorRadius(MemorySegment seg) {
        return (float)constants$80.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxHorRadius;
     * }
     */
    public static void maxHorRadius(MemorySegment seg, float x) {
        constants$80.const$0.set(seg, x);
    }
    public static float maxHorRadiusAtIndex(MemorySegment seg, long index) {
        return (float)constants$80.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void maxHorRadiusAtIndex(MemorySegment seg, long index, float x) {
        constants$80.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle verticalRadiusDefaultFactor$VH() {
        return constants$80.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float verticalRadiusDefaultFactor;
     * }
     */
    public static float verticalRadiusDefaultFactor(MemorySegment seg) {
        return (float)constants$80.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float verticalRadiusDefaultFactor;
     * }
     */
    public static void verticalRadiusDefaultFactor(MemorySegment seg, float x) {
        constants$80.const$1.set(seg, x);
    }
    public static float verticalRadiusDefaultFactorAtIndex(MemorySegment seg, long index) {
        return (float)constants$80.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void verticalRadiusDefaultFactorAtIndex(MemorySegment seg, long index, float x) {
        constants$80.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle verticalRadiusCenterFactor$VH() {
        return constants$80.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float verticalRadiusCenterFactor;
     * }
     */
    public static float verticalRadiusCenterFactor(MemorySegment seg) {
        return (float)constants$80.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float verticalRadiusCenterFactor;
     * }
     */
    public static void verticalRadiusCenterFactor(MemorySegment seg, float x) {
        constants$80.const$2.set(seg, x);
    }
    public static float verticalRadiusCenterFactorAtIndex(MemorySegment seg, long index) {
        return (float)constants$80.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void verticalRadiusCenterFactorAtIndex(MemorySegment seg, long index, float x) {
        constants$80.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}