// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct CaveCarverConfig {
 *     int dim;
 *     float probability;
 *     int carverIndex;
 *     int range;
 *     int caveBound;
 *     float (*thickness)(uint64_t*);
 *     double tunnelYScale;
 *     int (*y)(uint64_t*,int,int,int);
 *     int minY;
 *     int maxY;
 *     int innerY;
 *     float (*yScale)(uint64_t*,float,float);
 *     float minYScale;
 *     float maxYScale;
 *     float (*horizontalRadiusMultiplier)(uint64_t*,float,float);
 *     float minHorRadius;
 *     float maxHorRadius;
 *     float (*verticalRadiusMultiplier)(uint64_t*,float,float);
 *     float minVerRadius;
 *     float maxVerRadius;
 *     float (*floorLevel)(uint64_t*,float,float);
 *     float minFloorLevel;
 *     float maxFloorLevel;
 * };
 * }
 */
public class CaveCarverConfig {

    public static MemoryLayout $LAYOUT() {
        return constants$80.const$3;
    }
    public static VarHandle dim$VH() {
        return constants$80.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int dim;
     * }
     */
    public static int dim(MemorySegment seg) {
        return (int)constants$80.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int dim;
     * }
     */
    public static void dim(MemorySegment seg, int x) {
        constants$80.const$4.set(seg, x);
    }
    public static int dimAtIndex(MemorySegment seg, long index) {
        return (int)constants$80.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void dimAtIndex(MemorySegment seg, long index, int x) {
        constants$80.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle probability$VH() {
        return constants$80.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float probability;
     * }
     */
    public static float probability(MemorySegment seg) {
        return (float)constants$80.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float probability;
     * }
     */
    public static void probability(MemorySegment seg, float x) {
        constants$80.const$5.set(seg, x);
    }
    public static float probabilityAtIndex(MemorySegment seg, long index) {
        return (float)constants$80.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void probabilityAtIndex(MemorySegment seg, long index, float x) {
        constants$80.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle carverIndex$VH() {
        return constants$81.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int carverIndex;
     * }
     */
    public static int carverIndex(MemorySegment seg) {
        return (int)constants$81.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int carverIndex;
     * }
     */
    public static void carverIndex(MemorySegment seg, int x) {
        constants$81.const$0.set(seg, x);
    }
    public static int carverIndexAtIndex(MemorySegment seg, long index) {
        return (int)constants$81.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void carverIndexAtIndex(MemorySegment seg, long index, int x) {
        constants$81.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle range$VH() {
        return constants$81.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int range;
     * }
     */
    public static int range(MemorySegment seg) {
        return (int)constants$81.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int range;
     * }
     */
    public static void range(MemorySegment seg, int x) {
        constants$81.const$1.set(seg, x);
    }
    public static int rangeAtIndex(MemorySegment seg, long index) {
        return (int)constants$81.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void rangeAtIndex(MemorySegment seg, long index, int x) {
        constants$81.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle caveBound$VH() {
        return constants$81.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int caveBound;
     * }
     */
    public static int caveBound(MemorySegment seg) {
        return (int)constants$81.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int caveBound;
     * }
     */
    public static void caveBound(MemorySegment seg, int x) {
        constants$81.const$2.set(seg, x);
    }
    public static int caveBoundAtIndex(MemorySegment seg, long index) {
        return (int)constants$81.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void caveBoundAtIndex(MemorySegment seg, long index, int x) {
        constants$81.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*thickness)(uint64_t*);
     * }
     */
    public interface thickness {

        float apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(thickness fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$81.const$3, fi, constants$2.const$5, scope);
        }
        static thickness ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (float)constants$3.const$1.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle thickness$VH() {
        return constants$81.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*thickness)(uint64_t*);
     * }
     */
    public static MemorySegment thickness(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$81.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*thickness)(uint64_t*);
     * }
     */
    public static void thickness(MemorySegment seg, MemorySegment x) {
        constants$81.const$4.set(seg, x);
    }
    public static MemorySegment thicknessAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$81.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void thicknessAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$81.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static thickness thickness(MemorySegment segment, Arena scope) {
        return thickness.ofAddress(thickness(segment), scope);
    }
    public static VarHandle tunnelYScale$VH() {
        return constants$81.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double tunnelYScale;
     * }
     */
    public static double tunnelYScale(MemorySegment seg) {
        return (double)constants$81.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double tunnelYScale;
     * }
     */
    public static void tunnelYScale(MemorySegment seg, double x) {
        constants$81.const$5.set(seg, x);
    }
    public static double tunnelYScaleAtIndex(MemorySegment seg, long index) {
        return (double)constants$81.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void tunnelYScaleAtIndex(MemorySegment seg, long index, double x) {
        constants$81.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * int (*y)(uint64_t*,int,int,int);
     * }
     */
    public interface y {

        int apply(java.lang.foreign.MemorySegment _x0, int _x1, int _x2, int _x3);
        static MemorySegment allocate(y fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$82.const$0, fi, constants$71.const$1, scope);
        }
        static y ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, int __x1, int __x2, int __x3) -> {
                try {
                    return (int)constants$75.const$3.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle y$VH() {
        return constants$82.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*y)(uint64_t*,int,int,int);
     * }
     */
    public static MemorySegment y(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$82.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*y)(uint64_t*,int,int,int);
     * }
     */
    public static void y(MemorySegment seg, MemorySegment x) {
        constants$82.const$1.set(seg, x);
    }
    public static MemorySegment yAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$82.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void yAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$82.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static y y(MemorySegment segment, Arena scope) {
        return y.ofAddress(y(segment), scope);
    }
    public static VarHandle minY$VH() {
        return constants$82.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int minY;
     * }
     */
    public static int minY(MemorySegment seg) {
        return (int)constants$82.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int minY;
     * }
     */
    public static void minY(MemorySegment seg, int x) {
        constants$82.const$2.set(seg, x);
    }
    public static int minYAtIndex(MemorySegment seg, long index) {
        return (int)constants$82.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void minYAtIndex(MemorySegment seg, long index, int x) {
        constants$82.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxY$VH() {
        return constants$82.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int maxY;
     * }
     */
    public static int maxY(MemorySegment seg) {
        return (int)constants$82.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int maxY;
     * }
     */
    public static void maxY(MemorySegment seg, int x) {
        constants$82.const$3.set(seg, x);
    }
    public static int maxYAtIndex(MemorySegment seg, long index) {
        return (int)constants$82.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void maxYAtIndex(MemorySegment seg, long index, int x) {
        constants$82.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle innerY$VH() {
        return constants$82.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int innerY;
     * }
     */
    public static int innerY(MemorySegment seg) {
        return (int)constants$82.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int innerY;
     * }
     */
    public static void innerY(MemorySegment seg, int x) {
        constants$82.const$4.set(seg, x);
    }
    public static int innerYAtIndex(MemorySegment seg, long index) {
        return (int)constants$82.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void innerYAtIndex(MemorySegment seg, long index, int x) {
        constants$82.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*yScale)(uint64_t*,float,float);
     * }
     */
    public interface yScale {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2);
        static MemorySegment allocate(yScale fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$82.const$5, fi, constants$76.const$3, scope);
        }
        static yScale ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2) -> {
                try {
                    return (float)constants$76.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle yScale$VH() {
        return constants$83.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*yScale)(uint64_t*,float,float);
     * }
     */
    public static MemorySegment yScale(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$83.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*yScale)(uint64_t*,float,float);
     * }
     */
    public static void yScale(MemorySegment seg, MemorySegment x) {
        constants$83.const$0.set(seg, x);
    }
    public static MemorySegment yScaleAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$83.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void yScaleAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$83.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static yScale yScale(MemorySegment segment, Arena scope) {
        return yScale.ofAddress(yScale(segment), scope);
    }
    public static VarHandle minYScale$VH() {
        return constants$83.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minYScale;
     * }
     */
    public static float minYScale(MemorySegment seg) {
        return (float)constants$83.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minYScale;
     * }
     */
    public static void minYScale(MemorySegment seg, float x) {
        constants$83.const$1.set(seg, x);
    }
    public static float minYScaleAtIndex(MemorySegment seg, long index) {
        return (float)constants$83.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void minYScaleAtIndex(MemorySegment seg, long index, float x) {
        constants$83.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxYScale$VH() {
        return constants$83.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxYScale;
     * }
     */
    public static float maxYScale(MemorySegment seg) {
        return (float)constants$83.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxYScale;
     * }
     */
    public static void maxYScale(MemorySegment seg, float x) {
        constants$83.const$2.set(seg, x);
    }
    public static float maxYScaleAtIndex(MemorySegment seg, long index) {
        return (float)constants$83.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void maxYScaleAtIndex(MemorySegment seg, long index, float x) {
        constants$83.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*horizontalRadiusMultiplier)(uint64_t*,float,float);
     * }
     */
    public interface horizontalRadiusMultiplier {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2);
        static MemorySegment allocate(horizontalRadiusMultiplier fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$83.const$3, fi, constants$76.const$3, scope);
        }
        static horizontalRadiusMultiplier ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2) -> {
                try {
                    return (float)constants$76.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle horizontalRadiusMultiplier$VH() {
        return constants$83.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*horizontalRadiusMultiplier)(uint64_t*,float,float);
     * }
     */
    public static MemorySegment horizontalRadiusMultiplier(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$83.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*horizontalRadiusMultiplier)(uint64_t*,float,float);
     * }
     */
    public static void horizontalRadiusMultiplier(MemorySegment seg, MemorySegment x) {
        constants$83.const$4.set(seg, x);
    }
    public static MemorySegment horizontalRadiusMultiplierAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$83.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void horizontalRadiusMultiplierAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$83.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static horizontalRadiusMultiplier horizontalRadiusMultiplier(MemorySegment segment, Arena scope) {
        return horizontalRadiusMultiplier.ofAddress(horizontalRadiusMultiplier(segment), scope);
    }
    public static VarHandle minHorRadius$VH() {
        return constants$83.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minHorRadius;
     * }
     */
    public static float minHorRadius(MemorySegment seg) {
        return (float)constants$83.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minHorRadius;
     * }
     */
    public static void minHorRadius(MemorySegment seg, float x) {
        constants$83.const$5.set(seg, x);
    }
    public static float minHorRadiusAtIndex(MemorySegment seg, long index) {
        return (float)constants$83.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void minHorRadiusAtIndex(MemorySegment seg, long index, float x) {
        constants$83.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxHorRadius$VH() {
        return constants$84.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxHorRadius;
     * }
     */
    public static float maxHorRadius(MemorySegment seg) {
        return (float)constants$84.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxHorRadius;
     * }
     */
    public static void maxHorRadius(MemorySegment seg, float x) {
        constants$84.const$0.set(seg, x);
    }
    public static float maxHorRadiusAtIndex(MemorySegment seg, long index) {
        return (float)constants$84.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void maxHorRadiusAtIndex(MemorySegment seg, long index, float x) {
        constants$84.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*verticalRadiusMultiplier)(uint64_t*,float,float);
     * }
     */
    public interface verticalRadiusMultiplier {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2);
        static MemorySegment allocate(verticalRadiusMultiplier fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$84.const$1, fi, constants$76.const$3, scope);
        }
        static verticalRadiusMultiplier ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2) -> {
                try {
                    return (float)constants$76.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle verticalRadiusMultiplier$VH() {
        return constants$84.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*verticalRadiusMultiplier)(uint64_t*,float,float);
     * }
     */
    public static MemorySegment verticalRadiusMultiplier(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$84.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*verticalRadiusMultiplier)(uint64_t*,float,float);
     * }
     */
    public static void verticalRadiusMultiplier(MemorySegment seg, MemorySegment x) {
        constants$84.const$2.set(seg, x);
    }
    public static MemorySegment verticalRadiusMultiplierAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$84.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void verticalRadiusMultiplierAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$84.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static verticalRadiusMultiplier verticalRadiusMultiplier(MemorySegment segment, Arena scope) {
        return verticalRadiusMultiplier.ofAddress(verticalRadiusMultiplier(segment), scope);
    }
    public static VarHandle minVerRadius$VH() {
        return constants$84.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minVerRadius;
     * }
     */
    public static float minVerRadius(MemorySegment seg) {
        return (float)constants$84.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minVerRadius;
     * }
     */
    public static void minVerRadius(MemorySegment seg, float x) {
        constants$84.const$3.set(seg, x);
    }
    public static float minVerRadiusAtIndex(MemorySegment seg, long index) {
        return (float)constants$84.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void minVerRadiusAtIndex(MemorySegment seg, long index, float x) {
        constants$84.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxVerRadius$VH() {
        return constants$84.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxVerRadius;
     * }
     */
    public static float maxVerRadius(MemorySegment seg) {
        return (float)constants$84.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxVerRadius;
     * }
     */
    public static void maxVerRadius(MemorySegment seg, float x) {
        constants$84.const$4.set(seg, x);
    }
    public static float maxVerRadiusAtIndex(MemorySegment seg, long index) {
        return (float)constants$84.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void maxVerRadiusAtIndex(MemorySegment seg, long index, float x) {
        constants$84.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * float (*floorLevel)(uint64_t*,float,float);
     * }
     */
    public interface floorLevel {

        float apply(java.lang.foreign.MemorySegment _x0, float _x1, float _x2);
        static MemorySegment allocate(floorLevel fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$84.const$5, fi, constants$76.const$3, scope);
        }
        static floorLevel ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, float __x1, float __x2) -> {
                try {
                    return (float)constants$76.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle floorLevel$VH() {
        return constants$85.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*floorLevel)(uint64_t*,float,float);
     * }
     */
    public static MemorySegment floorLevel(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$85.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*floorLevel)(uint64_t*,float,float);
     * }
     */
    public static void floorLevel(MemorySegment seg, MemorySegment x) {
        constants$85.const$0.set(seg, x);
    }
    public static MemorySegment floorLevelAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$85.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void floorLevelAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$85.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static floorLevel floorLevel(MemorySegment segment, Arena scope) {
        return floorLevel.ofAddress(floorLevel(segment), scope);
    }
    public static VarHandle minFloorLevel$VH() {
        return constants$85.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minFloorLevel;
     * }
     */
    public static float minFloorLevel(MemorySegment seg) {
        return (float)constants$85.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minFloorLevel;
     * }
     */
    public static void minFloorLevel(MemorySegment seg, float x) {
        constants$85.const$1.set(seg, x);
    }
    public static float minFloorLevelAtIndex(MemorySegment seg, long index) {
        return (float)constants$85.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void minFloorLevelAtIndex(MemorySegment seg, long index, float x) {
        constants$85.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxFloorLevel$VH() {
        return constants$85.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxFloorLevel;
     * }
     */
    public static float maxFloorLevel(MemorySegment seg) {
        return (float)constants$85.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxFloorLevel;
     * }
     */
    public static void maxFloorLevel(MemorySegment seg, float x) {
        constants$85.const$2.set(seg, x);
    }
    public static float maxFloorLevelAtIndex(MemorySegment seg, long index) {
        return (float)constants$85.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void maxFloorLevelAtIndex(MemorySegment seg, long index, float x) {
        constants$85.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}