// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final VarHandle const$0 = constants$26.const$5.varHandle(MemoryLayout.PathElement.groupElement("len"));
    static final VarHandle const$1 = constants$26.const$5.varHandle(MemoryLayout.PathElement.groupElement("val"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(42, MemoryLayout.structLayout(
            JAVA_INT.withName("len"),
            JAVA_INT.withName("typ"),
            MemoryLayout.sequenceLayout(12, JAVA_FLOAT).withName("loc"),
            MemoryLayout.sequenceLayout(12, JAVA_FLOAT).withName("der"),
            MemoryLayout.sequenceLayout(12, RuntimeHelper.POINTER).withName("val")
        ).withName("Spline")).withName("stack"),
        MemoryLayout.sequenceLayout(151, MemoryLayout.structLayout(
            JAVA_INT.withName("len"),
            JAVA_FLOAT.withName("val")
        ).withName("FixSpline")).withName("fstack"),
        JAVA_INT.withName("len"),
        JAVA_INT.withName("flen")
    ).withName("SplineStack");
    static final VarHandle const$3 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("len"));
    static final VarHandle const$4 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("flen"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(6, MemoryLayout.structLayout(
            JAVA_DOUBLE.withName("amplitude"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("octcnt"),
                MemoryLayout.paddingLayout(4),
                RuntimeHelper.POINTER.withName("octaves")
            ).withName("octA"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("octcnt"),
                MemoryLayout.paddingLayout(4),
                RuntimeHelper.POINTER.withName("octaves")
            ).withName("octB")
        ).withName("DoublePerlinNoise")).withName("climate"),
        MemoryLayout.sequenceLayout(46, MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(257, JAVA_BYTE).withName("d"),
            JAVA_BYTE.withName("h2"),
            MemoryLayout.paddingLayout(6),
            JAVA_DOUBLE.withName("a"),
            JAVA_DOUBLE.withName("b"),
            JAVA_DOUBLE.withName("c"),
            JAVA_DOUBLE.withName("amplitude"),
            JAVA_DOUBLE.withName("lacunarity"),
            JAVA_DOUBLE.withName("d2"),
            JAVA_DOUBLE.withName("t2")
        ).withName("PerlinNoise")).withName("oct"),
        RuntimeHelper.POINTER.withName("sp"),
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(42, MemoryLayout.structLayout(
                JAVA_INT.withName("len"),
                JAVA_INT.withName("typ"),
                MemoryLayout.sequenceLayout(12, JAVA_FLOAT).withName("loc"),
                MemoryLayout.sequenceLayout(12, JAVA_FLOAT).withName("der"),
                MemoryLayout.sequenceLayout(12, RuntimeHelper.POINTER).withName("val")
            ).withName("Spline")).withName("stack"),
            MemoryLayout.sequenceLayout(151, MemoryLayout.structLayout(
                JAVA_INT.withName("len"),
                JAVA_FLOAT.withName("val")
            ).withName("FixSpline")).withName("fstack"),
            JAVA_INT.withName("len"),
            JAVA_INT.withName("flen")
        ).withName("ss"),
        JAVA_INT.withName("nptype"),
        JAVA_INT.withName("mc")
    ).withName("BiomeNoise");
}


