// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$106 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$106() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "create_enchant_with_levels",
        constants$106.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "get_enchantment_name",
        constants$96.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "test_enchant_vec",
        constants$106.const$3
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("min_rolls"),
        JAVA_INT.withName("max_rolls"),
        RuntimeHelper.POINTER.withName("roll_count_function"),
        JAVA_INT.withName("total_weight"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("precomputed_loot"),
        JAVA_INT.withName("entry_count"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("entry_to_item"),
        RuntimeHelper.POINTER.withName("entry_functions_index"),
        RuntimeHelper.POINTER.withName("entry_functions_count"),
        RuntimeHelper.POINTER.withName("loot_functions")
    ).withName("LootPool");
}


