// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("scale"),
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z"),
            JAVA_INT.withName("sx"),
            JAVA_INT.withName("sz"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("sy")
        ).withName("Range"),
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mapNether3D",
        constants$34.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("scale"),
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z"),
            JAVA_INT.withName("sx"),
            JAVA_INT.withName("sz"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("sy")
        ).withName("Range"),
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "genNetherScaled",
        constants$34.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setEndSeed",
        constants$32.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mapEndBiome",
        constants$13.const$3
    );
}


