// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$107 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$107() {}
    static final VarHandle const$0 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("min_rolls"));
    static final VarHandle const$1 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("max_rolls"));
    static final VarHandle const$2 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("roll_count_function"));
    static final VarHandle const$3 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("total_weight"));
    static final VarHandle const$4 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("precomputed_loot"));
    static final VarHandle const$5 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("entry_count"));
}


