// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    static final VarHandle const$0 = constants$49.const$4.varHandle(MemoryLayout.PathElement.groupElement("decoratorIndex"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("z")
    ).withName("Pos");
    static final VarHandle const$2 = constants$50.const$1.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$3 = constants$50.const$1.varHandle(MemoryLayout.PathElement.groupElement("z"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("z")
    ).withName("Pos3");
    static final VarHandle const$5 = constants$50.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
}


