// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final VarHandle const$0 = constants$25.const$5.varHandle(MemoryLayout.PathElement.groupElement("contASample"));
    static final VarHandle const$1 = constants$25.const$5.varHandle(MemoryLayout.PathElement.groupElement("contBSample"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("len"),
        JAVA_INT.withName("typ"),
        MemoryLayout.sequenceLayout(12, JAVA_FLOAT).withName("loc"),
        MemoryLayout.sequenceLayout(12, JAVA_FLOAT).withName("der"),
        MemoryLayout.sequenceLayout(12, RuntimeHelper.POINTER).withName("val")
    ).withName("Spline");
    static final VarHandle const$3 = constants$26.const$2.varHandle(MemoryLayout.PathElement.groupElement("len"));
    static final VarHandle const$4 = constants$26.const$2.varHandle(MemoryLayout.PathElement.groupElement("typ"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("len"),
        JAVA_FLOAT.withName("val")
    ).withName("FixSpline");
}


