// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final VarHandle const$0 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("edgesToExcl"));
    static final VarHandle const$1 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("raresToExcl"));
    static final VarHandle const$2 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("raresToExclM"));
    static final VarHandle const$3 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("shoreToExcl"));
    static final VarHandle const$4 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("shoreToExclM"));
    static final VarHandle const$5 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("riverToExcl"));
}


