// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getFixedEndGateways",
        constants$90.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("z")
    ).withName("Pos"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z")
        ).withName("Pos"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getLinkedGatewayChunk",
        constants$90.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("z")
    ).withName("Pos"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z")
        ).withName("Pos")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getLinkedGatewayPos",
        constants$90.const$4
    );
}


