// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("fun"),
        RuntimeHelper.POINTER.withName("params"),
        MemoryLayout.sequenceLayout(2, JAVA_INT).withName("params_int"),
        RuntimeHelper.POINTER.withName("varparams_int"),
        RuntimeHelper.POINTER.withName("varparams_int_arr"),
        JAVA_INT.withName("varparams_int_arr_size"),
        MemoryLayout.paddingLayout(4)
    ).withName("LootFunction");
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(LootFunction.fun.class, "apply", constants$103.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$103.const$1
    );
    static final VarHandle const$4 = constants$103.const$0.varHandle(MemoryLayout.PathElement.groupElement("fun"));
    static final VarHandle const$5 = constants$103.const$0.varHandle(MemoryLayout.PathElement.groupElement("params"));
}


