// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$77 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$77() {}
    static final VarHandle const$0 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("verticalRotation"));
    static final VarHandle const$1 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("minVerRot"));
    static final VarHandle const$2 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("maxVerRot"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(CanyonCarverConfig.distanceFactor.class, "apply", constants$76.const$3);
    static final VarHandle const$4 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("distanceFactor"));
    static final VarHandle const$5 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("minDistance"));
}


