// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$68 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$68() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("index"),
        JAVA_INT.withName("step"),
        JAVA_INT.withName("size"),
        JAVA_INT.withName("repeatCount"),
        RuntimeHelper.POINTER.withName("heightProvider"),
        JAVA_INT.withName("h1"),
        JAVA_INT.withName("h2"),
        JAVA_INT.withName("h3"),
        JAVA_INT.withName("oreType"),
        JAVA_INT.withName("oreBlock"),
        JAVA_BYTE.withName("dim"),
        JAVA_BYTE.withName("numReplaceBlocks"),
        MemoryLayout.paddingLayout(2),
        RuntimeHelper.POINTER.withName("replaceBlocks"),
        JAVA_FLOAT.withName("discardChanceOnAirExposure"),
        MemoryLayout.paddingLayout(4)
    ).withName("OreConfig");
    static final VarHandle const$1 = constants$68.const$0.varHandle(MemoryLayout.PathElement.groupElement("index"));
    static final VarHandle const$2 = constants$68.const$0.varHandle(MemoryLayout.PathElement.groupElement("step"));
    static final VarHandle const$3 = constants$68.const$0.varHandle(MemoryLayout.PathElement.groupElement("size"));
    static final VarHandle const$4 = constants$68.const$0.varHandle(MemoryLayout.PathElement.groupElement("repeatCount"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("state"),
            RuntimeHelper.POINTER.withName("setSeed"),
            RuntimeHelper.POINTER.withName("nextLong"),
            RuntimeHelper.POINTER.withName("nextInt"),
            RuntimeHelper.POINTER.withName("nextFloat"),
            RuntimeHelper.POINTER.withName("nextDouble"),
            RuntimeHelper.POINTER.withName("nextIntBetween")
        ).withName("RandomSource"),
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
}


