// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$91 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$91() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getHouseList",
        constants$91.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(monteCarloBiomes$eval.class, "apply", constants$91.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$91.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("scale"),
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z"),
            JAVA_INT.withName("sx"),
            JAVA_INT.withName("sz"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("sy")
        ).withName("Range"),
        RuntimeHelper.POINTER,
        JAVA_DOUBLE,
        JAVA_DOUBLE,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "monteCarloBiomes",
        constants$91.const$5
    );
}


