// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final VarHandle const$0 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("carverIndex"));
    static final VarHandle const$1 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("range"));
    static final VarHandle const$2 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("caveBound"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(CaveCarverConfig.thickness.class, "apply", constants$2.const$5);
    static final VarHandle const$4 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("thickness"));
    static final VarHandle const$5 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("tunnelYScale"));
}


