// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$80 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$80() {}
    static final VarHandle const$0 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("maxHorRadius"));
    static final VarHandle const$1 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("verticalRadiusDefaultFactor"));
    static final VarHandle const$2 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("verticalRadiusCenterFactor"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("dim"),
        JAVA_FLOAT.withName("probability"),
        JAVA_INT.withName("carverIndex"),
        JAVA_INT.withName("range"),
        JAVA_INT.withName("caveBound"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("thickness"),
        JAVA_DOUBLE.withName("tunnelYScale"),
        RuntimeHelper.POINTER.withName("y"),
        JAVA_INT.withName("minY"),
        JAVA_INT.withName("maxY"),
        JAVA_INT.withName("innerY"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("yScale"),
        JAVA_FLOAT.withName("minYScale"),
        JAVA_FLOAT.withName("maxYScale"),
        RuntimeHelper.POINTER.withName("horizontalRadiusMultiplier"),
        JAVA_FLOAT.withName("minHorRadius"),
        JAVA_FLOAT.withName("maxHorRadius"),
        RuntimeHelper.POINTER.withName("verticalRadiusMultiplier"),
        JAVA_FLOAT.withName("minVerRadius"),
        JAVA_FLOAT.withName("maxVerRadius"),
        RuntimeHelper.POINTER.withName("floorLevel"),
        JAVA_FLOAT.withName("minFloorLevel"),
        JAVA_FLOAT.withName("maxFloorLevel")
    ).withName("CaveCarverConfig");
    static final VarHandle const$4 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("dim"));
    static final VarHandle const$5 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("probability"));
}


