// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "createPos3List",
        constants$36.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("z")
        ).withName("Pos3")
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "appendPos3List",
        constants$52.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "freePos3List",
        constants$52.const$3
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z")
        ).withName("pos"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z")
        ).withName("nextapprox"),
        JAVA_INT.withName("index"),
        JAVA_INT.withName("ringnum"),
        JAVA_INT.withName("ringmax"),
        JAVA_INT.withName("ringidx"),
        JAVA_DOUBLE.withName("angle"),
        JAVA_DOUBLE.withName("dist"),
        JAVA_LONG.withName("rnds"),
        JAVA_INT.withName("mc"),
        MemoryLayout.paddingLayout(4)
    ).withName("StrongholdIter");
}


