// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("scale"),
        JAVA_INT.withName("x"),
        JAVA_INT.withName("z"),
        JAVA_INT.withName("sx"),
        JAVA_INT.withName("sz"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("sy")
    ).withName("Range");
    static final VarHandle const$1 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("scale"));
    static final VarHandle const$2 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$3 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("z"));
    static final VarHandle const$4 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("sx"));
    static final VarHandle const$5 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("sz"));
}


