// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("d2"));
    static final VarHandle const$1 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("t2"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("octcnt"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("octaves")
    ).withName("OctaveNoise");
    static final VarHandle const$3 = constants$6.const$2.varHandle(MemoryLayout.PathElement.groupElement("octcnt"));
    static final VarHandle const$4 = constants$6.const$2.varHandle(MemoryLayout.PathElement.groupElement("octaves"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_DOUBLE.withName("amplitude"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("octcnt"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("octaves")
        ).withName("octA"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("octcnt"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("octaves")
        ).withName("octB")
    ).withName("DoublePerlinNoise");
}


