// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final VarHandle const$0 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("index"));
    static final VarHandle const$1 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("ringnum"));
    static final VarHandle const$2 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("ringmax"));
    static final VarHandle const$3 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("ringidx"));
    static final VarHandle const$4 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("angle"));
    static final VarHandle const$5 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("dist"));
}


