// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$87 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$87() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("pos3s"),
        JAVA_INT.withName("capacity"),
        JAVA_INT.withName("size")
    ).withName("Pos3List"),
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("dim"),
            JAVA_FLOAT.withName("probability"),
            JAVA_INT.withName("carverIndex"),
            JAVA_INT.withName("range"),
            JAVA_INT.withName("caveBound"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("thickness"),
            JAVA_DOUBLE.withName("tunnelYScale"),
            RuntimeHelper.POINTER.withName("y"),
            JAVA_INT.withName("minY"),
            JAVA_INT.withName("maxY"),
            JAVA_INT.withName("innerY"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("yScale"),
            JAVA_FLOAT.withName("minYScale"),
            JAVA_FLOAT.withName("maxYScale"),
            RuntimeHelper.POINTER.withName("horizontalRadiusMultiplier"),
            JAVA_FLOAT.withName("minHorRadius"),
            JAVA_FLOAT.withName("maxHorRadius"),
            RuntimeHelper.POINTER.withName("verticalRadiusMultiplier"),
            JAVA_FLOAT.withName("minVerRadius"),
            JAVA_FLOAT.withName("maxVerRadius"),
            RuntimeHelper.POINTER.withName("floorLevel"),
            JAVA_FLOAT.withName("minFloorLevel"),
            JAVA_FLOAT.withName("maxFloorLevel")
        ).withName("CaveCarverConfig")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "carveCave",
        constants$87.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("z")
    ).withName("Pos"),
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "locateBiome",
        constants$87.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "isViableStructurePos",
        constants$87.const$4
    );
}


