// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$111 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$111() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "set_loot_seed",
        constants$0.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "set_internal_loot_seed",
        constants$0.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "get_item_id",
        constants$67.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "get_global_item_id",
        constants$2.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "get_item_name",
        constants$47.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "has_item",
        constants$2.const$1
    );
}


