// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$113 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$113() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "init_buried_treasure",
        constants$2.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "init_desert_pyramid",
        constants$2.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "init_end_city_treasure",
        constants$2.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "init_igloo_chest",
        constants$2.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "init_nether_bridge",
        constants$2.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "init_pillager_outpost",
        constants$2.const$1
    );
}


