// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$112 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$112() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "generate_loot",
        constants$52.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "get_item_type",
        constants$97.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "get_enchantment_from_name",
        constants$97.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "free_loot_function",
        constants$52.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "init_loot_table_name",
        constants$112.const$4
    );
}


