// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mapHeat",
        constants$13.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mapSpecial",
        constants$13.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mapMushroom",
        constants$13.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mapDeepOcean",
        constants$13.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mapBiome",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mapBamboo",
        constants$13.const$3
    );
}


