// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mapLand16",
        constants$13.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mapLandB18",
        constants$13.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mapIsland",
        constants$13.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mapSnow",
        constants$13.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mapSnow16",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mapCool",
        constants$13.const$3
    );
}


