// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$42 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$42() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sampleCaveEntrance",
        constants$32.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_DOUBLE,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_DOUBLE
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sampleEntrances",
        constants$42.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sampleCaveLayer",
        constants$32.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "sampleSlopedCheese",
        constants$32.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sampleCaveCheese",
        constants$42.const$1
    );
}


