// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "xDoublePerlinInit",
        constants$9.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sampleDoublePerlin",
        constants$9.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "biomeExists",
        constants$11.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "isOverworld",
        constants$11.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "getDimension",
        constants$11.const$5
    );
}


