// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$79 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$79() {}
    static final VarHandle const$0 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("maxThickness"));
    static final VarHandle const$1 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("plateauThickness"));
    static final VarHandle const$2 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("widthSmoothness"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(CanyonCarverConfig.horizontalRadiusFactor.class, "apply", constants$76.const$3);
    static final VarHandle const$4 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("horizontalRadiusFactor"));
    static final VarHandle const$5 = constants$74.const$3.varHandle(MemoryLayout.PathElement.groupElement("minHorRadius"));
}


