// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final VarHandle const$0 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("rnds"));
    static final VarHandle const$1 = constants$52.const$5.varHandle(MemoryLayout.PathElement.groupElement("mc"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("abandoned"),
        JAVA_BYTE.withName("giant"),
        JAVA_BYTE.withName("underground"),
        JAVA_BYTE.withName("airpocket"),
        JAVA_BYTE.withName("basement"),
        JAVA_BYTE.withName("cracked"),
        JAVA_BYTE.withName("size"),
        JAVA_BYTE.withName("start"),
        JAVA_SHORT.withName("biome"),
        JAVA_BYTE.withName("rotation"),
        JAVA_BYTE.withName("mirror"),
        JAVA_SHORT.withName("x"),
        JAVA_SHORT.withName("y"),
        JAVA_SHORT.withName("z"),
        JAVA_SHORT.withName("sx"),
        JAVA_SHORT.withName("sy"),
        JAVA_SHORT.withName("sz")
    ).withName("StructureVariant");
    static final VarHandle const$3 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("abandoned"));
    static final VarHandle const$4 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("giant"));
    static final VarHandle const$5 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("underground"));
}


