// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$73 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$73() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("oreBlock"),
        JAVA_INT.withName("rawOreBlock"),
        JAVA_INT.withName("fillerBlock"),
        JAVA_INT.withName("minY"),
        JAVA_INT.withName("maxY")
    ).withName("OreVeinConfig");
    static final VarHandle const$1 = constants$73.const$0.varHandle(MemoryLayout.PathElement.groupElement("oreBlock"));
    static final VarHandle const$2 = constants$73.const$0.varHandle(MemoryLayout.PathElement.groupElement("rawOreBlock"));
    static final VarHandle const$3 = constants$73.const$0.varHandle(MemoryLayout.PathElement.groupElement("fillerBlock"));
    static final VarHandle const$4 = constants$73.const$0.varHandle(MemoryLayout.PathElement.groupElement("minY"));
    static final VarHandle const$5 = constants$73.const$0.varHandle(MemoryLayout.PathElement.groupElement("maxY"));
}


