// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final VarHandle const$0 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("layerSalt"));
    static final VarHandle const$1 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("startSalt"));
    static final VarHandle const$2 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("startSeed"));
    static final VarHandle const$3 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("noise"));
    static final VarHandle const$4 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("data"));
    static final VarHandle const$5 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("p"));
}


