// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$59 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$59() {}
    static final VarHandle const$0 = constants$58.const$3.varHandle(MemoryLayout.PathElement.groupElement("z"));
    static final VarHandle const$1 = constants$58.const$3.varHandle(MemoryLayout.PathElement.groupElement("r"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("tempsToFind"),
        JAVA_LONG.withName("otempToFind"),
        JAVA_LONG.withName("majorToFind"),
        JAVA_LONG.withName("edgesToFind"),
        JAVA_LONG.withName("raresToFind"),
        JAVA_LONG.withName("raresToFindM"),
        JAVA_LONG.withName("shoreToFind"),
        JAVA_LONG.withName("shoreToFindM"),
        JAVA_LONG.withName("riverToFind"),
        JAVA_LONG.withName("riverToFindM"),
        JAVA_LONG.withName("oceanToFind"),
        JAVA_INT.withName("specialCnt"),
        JAVA_INT.withName("flags"),
        JAVA_LONG.withName("tempsToExcl"),
        JAVA_LONG.withName("majorToExcl"),
        JAVA_LONG.withName("edgesToExcl"),
        JAVA_LONG.withName("raresToExcl"),
        JAVA_LONG.withName("raresToExclM"),
        JAVA_LONG.withName("shoreToExcl"),
        JAVA_LONG.withName("shoreToExclM"),
        JAVA_LONG.withName("riverToExcl"),
        JAVA_LONG.withName("riverToExclM"),
        JAVA_LONG.withName("biomeToExcl"),
        JAVA_LONG.withName("biomeToExclM"),
        JAVA_LONG.withName("biomeToFind"),
        JAVA_LONG.withName("biomeToFindM"),
        JAVA_LONG.withName("biomeToPick"),
        JAVA_LONG.withName("biomeToPickM")
    ).withName("BiomeFilter");
    static final VarHandle const$3 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("tempsToFind"));
    static final VarHandle const$4 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("otempToFind"));
    static final VarHandle const$5 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("majorToFind"));
}


