// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$114 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$114() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "init_ruined_portal",
        constants$2.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "free_loot_table_pools",
        constants$52.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "init_loot_table",
        constants$112.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "init_loot_table_file",
        constants$112.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "resolve_subtable",
        constants$114.const$4
    );
}


