// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$58 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$58() {}
    static final VarHandle const$0 = constants$57.const$2.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$1 = constants$57.const$2.varHandle(MemoryLayout.PathElement.groupElement("chestCount"));
    static final VarHandle const$2 = constants$57.const$2.varHandle(MemoryLayout.PathElement.groupElement("next"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("z"),
        JAVA_INT.withName("r")
    ).withName("EndIsland");
    static final VarHandle const$4 = constants$58.const$3.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$5 = constants$58.const$3.varHandle(MemoryLayout.PathElement.groupElement("y"));
}


