// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final VarHandle const$0 = constants$0.const$3.varHandle(MemoryLayout.PathElement.groupElement("nextLong"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(RandomSource.nextInt.class, "apply", constants$2.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$2.const$1
    );
    static final VarHandle const$4 = constants$0.const$3.varHandle(MemoryLayout.PathElement.groupElement("nextInt"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
}


