// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$109 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$109() {}
    static final VarHandle const$0 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("item_count"));
    static final VarHandle const$1 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("item_names"));
    static final VarHandle const$2 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("global_item_ids"));
    static final VarHandle const$3 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("pool_count"));
    static final VarHandle const$4 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("loot_pools"));
    static final VarHandle const$5 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("unresolved_subtable_count"));
}


