// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$110 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$110() {}
    static final VarHandle const$0 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("subtable_count"));
    static final VarHandle const$1 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("subtable_pool_offset"));
    static final VarHandle const$2 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("subtable_pool_count"));
    static final VarHandle const$3 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("prng_state"));
    static final VarHandle const$4 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("generated_item_count"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(27, MemoryLayout.structLayout(
            JAVA_INT.withName("item"),
            JAVA_INT.withName("count"),
            JAVA_INT.withName("enchantment_count"),
            MemoryLayout.sequenceLayout(16, MemoryLayout.structLayout(
                JAVA_INT.withName("enchantment"),
                JAVA_INT.withName("level")
            ).withName("EnchantInstance")).withName("enchantments")
        ).withName("ItemStack")).withName("natural_loot"),
        MemoryLayout.sequenceLayout(27, MemoryLayout.structLayout(
            JAVA_INT.withName("item"),
            JAVA_INT.withName("count"),
            JAVA_INT.withName("enchantment_count"),
            MemoryLayout.sequenceLayout(16, MemoryLayout.structLayout(
                JAVA_INT.withName("enchantment"),
                JAVA_INT.withName("level")
            ).withName("EnchantInstance")).withName("enchantments")
        ).withName("ItemStack")).withName("indexed_loot"),
        MemoryLayout.sequenceLayout(64, JAVA_INT).withName("aggregated_loot")
    ).withName("LootTableOutput");
}


