// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$71 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$71() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getOreConfig",
        constants$64.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getBiomeForOreGen",
        constants$71.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "isViableOreBiome",
        constants$12.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("pos3s"),
        JAVA_INT.withName("capacity"),
        JAVA_INT.withName("size")
    ).withName("Pos3List"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index"),
            JAVA_INT.withName("step"),
            JAVA_INT.withName("size"),
            JAVA_INT.withName("repeatCount"),
            RuntimeHelper.POINTER.withName("heightProvider"),
            JAVA_INT.withName("h1"),
            JAVA_INT.withName("h2"),
            JAVA_INT.withName("h3"),
            JAVA_INT.withName("oreType"),
            JAVA_INT.withName("oreBlock"),
            JAVA_BYTE.withName("dim"),
            JAVA_BYTE.withName("numReplaceBlocks"),
            MemoryLayout.paddingLayout(2),
            RuntimeHelper.POINTER.withName("replaceBlocks"),
            JAVA_FLOAT.withName("discardChanceOnAirExposure"),
            MemoryLayout.paddingLayout(4)
        ).withName("OreConfig"),
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "generateOres",
        constants$71.const$4
    );
}


