// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$105 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$105() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "create_skip_calls",
        constants$36.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "create_no_op",
        constants$52.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "create_enchant_randomly_one_enchant",
        constants$36.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "create_enchant_randomly_list",
        constants$105.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "create_enchant_randomly",
        constants$105.const$5
    );
}


