// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$57 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$57() {}
    static final VarHandle const$0 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("sy"));
    static final VarHandle const$1 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("sz"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("name"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("z")
        ).withName("pos"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("z")
        ).withName("bb0"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("z")
        ).withName("bb1"),
        JAVA_BYTE.withName("rot"),
        JAVA_BYTE.withName("depth"),
        JAVA_BYTE.withName("type"),
        MemoryLayout.paddingLayout(1),
        JAVA_INT.withName("chestCount"),
        MemoryLayout.sequenceLayout(4, MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z")
        ).withName("Pos")).withName("chestPoses"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.sequenceLayout(4, JAVA_LONG).withName("lootSeeds"),
        MemoryLayout.sequenceLayout(4, RuntimeHelper.POINTER).withName("lootTables"),
        RuntimeHelper.POINTER.withName("next")
    ).withName("Piece");
    static final VarHandle const$3 = constants$57.const$2.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$4 = constants$57.const$2.varHandle(MemoryLayout.PathElement.groupElement("rot"));
    static final VarHandle const$5 = constants$57.const$2.varHandle(MemoryLayout.PathElement.groupElement("depth"));
}


