// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$85 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$85() {}
    static final VarHandle const$0 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("floorLevel"));
    static final VarHandle const$1 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("minFloorLevel"));
    static final VarHandle const$2 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("maxFloorLevel"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getCanyonCarverConfig",
        constants$64.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "isViableCanyonBiome",
        constants$11.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getCaveCarverConfig",
        constants$64.const$3
    );
}


