// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getMutated",
        constants$11.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getCategory",
        constants$11.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "areSimilar",
        constants$12.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "isMesa",
        constants$11.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "isShallowOcean",
        constants$11.const$5
    );
}


