// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$115 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$115() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "resolve_subtable_file",
        constants$114.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "free_loot_table",
        constants$52.const$3
    );
}


