// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    static final VarHandle const$0 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("entry_to_item"));
    static final VarHandle const$1 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("entry_functions_index"));
    static final VarHandle const$2 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("entry_functions_count"));
    static final VarHandle const$3 = constants$106.const$5.varHandle(MemoryLayout.PathElement.groupElement("loot_functions"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("version"),
        JAVA_INT.withName("item_count"),
        RuntimeHelper.POINTER.withName("item_names"),
        RuntimeHelper.POINTER.withName("global_item_ids"),
        JAVA_INT.withName("pool_count"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("loot_pools"),
        JAVA_INT.withName("unresolved_subtable_count"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.sequenceLayout(8, RuntimeHelper.POINTER).withName("unresolved_subtable_names"),
        JAVA_INT.withName("subtable_count"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("subtable_pool_offset"),
        RuntimeHelper.POINTER.withName("subtable_pool_count"),
        JAVA_LONG.withName("prng_state"),
        JAVA_INT.withName("generated_item_count"),
        MemoryLayout.sequenceLayout(27, MemoryLayout.structLayout(
            JAVA_INT.withName("item"),
            JAVA_INT.withName("count"),
            JAVA_INT.withName("enchantment_count"),
            MemoryLayout.sequenceLayout(16, MemoryLayout.structLayout(
                JAVA_INT.withName("enchantment"),
                JAVA_INT.withName("level")
            ).withName("EnchantInstance")).withName("enchantments")
        ).withName("ItemStack")).withName("generated_items")
    ).withName("LootTableContext");
    static final VarHandle const$5 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("version"));
}


