// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {}
    static final VarHandle const$0 = constants$50.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$1 = constants$50.const$4.varHandle(MemoryLayout.PathElement.groupElement("z"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("pos3s"),
        JAVA_INT.withName("capacity"),
        JAVA_INT.withName("size")
    ).withName("Pos3List");
    static final VarHandle const$3 = constants$51.const$2.varHandle(MemoryLayout.PathElement.groupElement("pos3s"));
    static final VarHandle const$4 = constants$51.const$2.varHandle(MemoryLayout.PathElement.groupElement("capacity"));
    static final VarHandle const$5 = constants$51.const$2.varHandle(MemoryLayout.PathElement.groupElement("size"));
}


