// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final VarHandle const$0 = constants$31.const$4.varHandle(MemoryLayout.PathElement.groupElement("jaggednessSpline"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "initSurfaceNoise",
        constants$32.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "initSurfaceNoiseBeta",
        constants$0.const$5
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_DOUBLE,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sampleSurfaceNoise",
        constants$32.const$4
    );
}


