// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("steps"),
        RuntimeHelper.POINTER.withName("param"),
        RuntimeHelper.POINTER.withName("nodes"),
        JAVA_INT.withName("order"),
        JAVA_INT.withName("len")
    ).withName("BiomeTree");
    static final VarHandle const$1 = constants$29.const$0.varHandle(MemoryLayout.PathElement.groupElement("steps"));
    static final VarHandle const$2 = constants$29.const$0.varHandle(MemoryLayout.PathElement.groupElement("param"));
    static final VarHandle const$3 = constants$29.const$0.varHandle(MemoryLayout.PathElement.groupElement("nodes"));
    static final VarHandle const$4 = constants$29.const$0.varHandle(MemoryLayout.PathElement.groupElement("order"));
    static final VarHandle const$5 = constants$29.const$0.varHandle(MemoryLayout.PathElement.groupElement("len"));
}


