// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "genArea",
        constants$13.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mapApproxHeight",
        constants$48.const$1
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("salt"),
        JAVA_BYTE.withName("regionSize"),
        JAVA_BYTE.withName("chunkRange"),
        JAVA_BYTE.withName("structType"),
        JAVA_BYTE.withName("dim"),
        JAVA_FLOAT.withName("rarity")
    ).withName("StructureConfig");
    static final VarHandle const$4 = constants$48.const$3.varHandle(MemoryLayout.PathElement.groupElement("salt"));
    static final VarHandle const$5 = constants$48.const$3.varHandle(MemoryLayout.PathElement.groupElement("regionSize"));
}


