// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_DOUBLE.withName("xzScale"),
        JAVA_DOUBLE.withName("yScale"),
        JAVA_DOUBLE.withName("xzFactor"),
        JAVA_DOUBLE.withName("yFactor"),
        JAVA_DOUBLE.withName("xzMultiplier"),
        JAVA_DOUBLE.withName("yMultiplier"),
        JAVA_DOUBLE.withName("smearScaleMultiplier"),
        JAVA_DOUBLE.withName("smearedYScale"),
        JAVA_DOUBLE.withName("factoredSmearedYScale"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("octcnt"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("octaves")
        ).withName("octmin"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("octcnt"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("octaves")
        ).withName("octmax"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("octcnt"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("octaves")
        ).withName("octmain"),
        MemoryLayout.sequenceLayout(40, MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(257, JAVA_BYTE).withName("d"),
            JAVA_BYTE.withName("h2"),
            MemoryLayout.paddingLayout(6),
            JAVA_DOUBLE.withName("a"),
            JAVA_DOUBLE.withName("b"),
            JAVA_DOUBLE.withName("c"),
            JAVA_DOUBLE.withName("amplitude"),
            JAVA_DOUBLE.withName("lacunarity"),
            JAVA_DOUBLE.withName("d2"),
            JAVA_DOUBLE.withName("t2")
        ).withName("PerlinNoise")).withName("oct")
    ).withName("BlendedNoise");
    static final VarHandle const$1 = constants$30.const$0.varHandle(MemoryLayout.PathElement.groupElement("xzScale"));
    static final VarHandle const$2 = constants$30.const$0.varHandle(MemoryLayout.PathElement.groupElement("yScale"));
    static final VarHandle const$3 = constants$30.const$0.varHandle(MemoryLayout.PathElement.groupElement("xzFactor"));
    static final VarHandle const$4 = constants$30.const$0.varHandle(MemoryLayout.PathElement.groupElement("yFactor"));
    static final VarHandle const$5 = constants$30.const$0.varHandle(MemoryLayout.PathElement.groupElement("xzMultiplier"));
}


