// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$60 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$60() {}
    static final VarHandle const$0 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("edgesToFind"));
    static final VarHandle const$1 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("raresToFind"));
    static final VarHandle const$2 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("raresToFindM"));
    static final VarHandle const$3 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("shoreToFind"));
    static final VarHandle const$4 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("shoreToFindM"));
    static final VarHandle const$5 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("riverToFind"));
}


