// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$98 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$98() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "biome2str",
        constants$96.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "struct2str",
        constants$96.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ore2str",
        constants$96.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "initBiomeColors",
        constants$52.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "initBiomeTypeColors",
        constants$52.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "parseBiomeColors",
        constants$67.const$0
    );
}


