// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sampleBase3dNoise",
        constants$32.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "initTerrainNoise",
        constants$40.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sampleSpaghettiRoughness",
        constants$32.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sampleSpaghetti2dThicknessModulator",
        constants$32.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "sampleSpaghetti2d",
        constants$32.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sampleSpaghetti3d",
        constants$32.const$4
    );
}


