// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(RandomSource.setSeed.class, "apply", constants$0.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$0.const$5
    );
    static final VarHandle const$2 = constants$0.const$3.varHandle(MemoryLayout.PathElement.groupElement("setSeed"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(RandomSource.nextLong.class, "apply", constants$1.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$1.const$3
    );
}


