// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$84 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$84() {}
    static final VarHandle const$0 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("maxHorRadius"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(CaveCarverConfig.verticalRadiusMultiplier.class, "apply", constants$76.const$3);
    static final VarHandle const$2 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("verticalRadiusMultiplier"));
    static final VarHandle const$3 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("minVerRadius"));
    static final VarHandle const$4 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("maxVerRadius"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(CaveCarverConfig.floorLevel.class, "apply", constants$76.const$3);
}


