// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$101 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$101() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("salt"),
            JAVA_BYTE.withName("regionSize"),
            JAVA_BYTE.withName("chunkRange"),
            JAVA_BYTE.withName("structType"),
            JAVA_BYTE.withName("dim"),
            JAVA_FLOAT.withName("rarity")
        ).withName("StructureConfig"),
        JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "scanForQuads",
        constants$101.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "item_name2global_id",
        constants$97.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "global_id2item_name",
        constants$96.const$2
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("enchantment"),
        JAVA_INT.withName("level")
    ).withName("EnchantInstance");
    static final VarHandle const$5 = constants$101.const$4.varHandle(MemoryLayout.PathElement.groupElement("enchantment"));
}


