// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final VarHandle const$0 = constants$16.const$1.varHandle(MemoryLayout.PathElement.groupElement("entry_256"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setLayerSeed",
        constants$0.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mapContinent",
        constants$13.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mapZoomFuzzy",
        constants$13.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mapZoom",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mapLand",
        constants$13.const$3
    );
}


