// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("getMap"),
        JAVA_BYTE.withName("mc"),
        JAVA_BYTE.withName("zoom"),
        JAVA_BYTE.withName("edge"),
        MemoryLayout.paddingLayout(1),
        JAVA_INT.withName("scale"),
        JAVA_LONG.withName("layerSalt"),
        JAVA_LONG.withName("startSalt"),
        JAVA_LONG.withName("startSeed"),
        RuntimeHelper.POINTER.withName("noise"),
        RuntimeHelper.POINTER.withName("data"),
        RuntimeHelper.POINTER.withName("p"),
        RuntimeHelper.POINTER.withName("p2")
    ).withName("Layer");
    static final VarHandle const$1 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("getMap"));
    static final VarHandle const$2 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("mc"));
    static final VarHandle const$3 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("zoom"));
    static final VarHandle const$4 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("edge"));
    static final VarHandle const$5 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("scale"));
}


