// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(CaveCarverConfig.y.class, "apply", constants$71.const$1);
    static final VarHandle const$1 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$2 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("minY"));
    static final VarHandle const$3 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("maxY"));
    static final VarHandle const$4 = constants$80.const$3.varHandle(MemoryLayout.PathElement.groupElement("innerY"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(CaveCarverConfig.yScale.class, "apply", constants$76.const$3);
}


