// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("scale"),
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z"),
            JAVA_INT.withName("sx"),
            JAVA_INT.withName("sz"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("sy")
        ).withName("Range")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "allocCache",
        constants$46.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("scale"),
            JAVA_INT.withName("x"),
            JAVA_INT.withName("z"),
            JAVA_INT.withName("sx"),
            JAVA_INT.withName("sz"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("sy")
        ).withName("Range")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "genBiomes",
        constants$46.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getBiomeAt",
        constants$46.const$4
    );
}


