// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$104 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$104() {}
    static final VarHandle const$0 = constants$103.const$0.varHandle(MemoryLayout.PathElement.groupElement("varparams_int"));
    static final VarHandle const$1 = constants$103.const$0.varHandle(MemoryLayout.PathElement.groupElement("varparams_int_arr"));
    static final VarHandle const$2 = constants$103.const$0.varHandle(MemoryLayout.PathElement.groupElement("varparams_int_arr_size"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "create_set_count",
        constants$45.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "create_set_effect",
        constants$52.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "create_set_damage",
        constants$52.const$3
    );
}


