// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "isViableCaveBiome",
        constants$11.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("dim"),
            JAVA_FLOAT.withName("probability"),
            JAVA_INT.withName("carverIndex"),
            JAVA_INT.withName("range"),
            RuntimeHelper.POINTER.withName("y"),
            JAVA_INT.withName("minY"),
            JAVA_INT.withName("maxY"),
            JAVA_INT.withName("innerY"),
            JAVA_FLOAT.withName("yScale"),
            RuntimeHelper.POINTER.withName("verticalRotation"),
            JAVA_FLOAT.withName("minVerRot"),
            JAVA_FLOAT.withName("maxVerRot"),
            RuntimeHelper.POINTER.withName("distanceFactor"),
            JAVA_FLOAT.withName("minDistance"),
            JAVA_FLOAT.withName("maxDistance"),
            RuntimeHelper.POINTER.withName("thickness"),
            JAVA_FLOAT.withName("minThickness"),
            JAVA_FLOAT.withName("maxThickness"),
            JAVA_FLOAT.withName("plateauThickness"),
            JAVA_INT.withName("widthSmoothness"),
            RuntimeHelper.POINTER.withName("horizontalRadiusFactor"),
            JAVA_FLOAT.withName("minHorRadius"),
            JAVA_FLOAT.withName("maxHorRadius"),
            JAVA_FLOAT.withName("verticalRadiusDefaultFactor"),
            JAVA_FLOAT.withName("verticalRadiusCenterFactor")
        ).withName("CanyonCarverConfig"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "checkCanyonStart",
        constants$86.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("dim"),
            JAVA_FLOAT.withName("probability"),
            JAVA_INT.withName("carverIndex"),
            JAVA_INT.withName("range"),
            JAVA_INT.withName("caveBound"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("thickness"),
            JAVA_DOUBLE.withName("tunnelYScale"),
            RuntimeHelper.POINTER.withName("y"),
            JAVA_INT.withName("minY"),
            JAVA_INT.withName("maxY"),
            JAVA_INT.withName("innerY"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("yScale"),
            JAVA_FLOAT.withName("minYScale"),
            JAVA_FLOAT.withName("maxYScale"),
            RuntimeHelper.POINTER.withName("horizontalRadiusMultiplier"),
            JAVA_FLOAT.withName("minHorRadius"),
            JAVA_FLOAT.withName("maxHorRadius"),
            RuntimeHelper.POINTER.withName("verticalRadiusMultiplier"),
            JAVA_FLOAT.withName("minVerRadius"),
            JAVA_FLOAT.withName("maxVerRadius"),
            RuntimeHelper.POINTER.withName("floorLevel"),
            JAVA_FLOAT.withName("minFloorLevel"),
            JAVA_FLOAT.withName("maxFloorLevel")
        ).withName("CaveCarverConfig"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "checkCaveStart",
        constants$86.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("pos3s"),
        JAVA_INT.withName("capacity"),
        JAVA_INT.withName("size")
    ).withName("Pos3List"),
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("dim"),
            JAVA_FLOAT.withName("probability"),
            JAVA_INT.withName("carverIndex"),
            JAVA_INT.withName("range"),
            RuntimeHelper.POINTER.withName("y"),
            JAVA_INT.withName("minY"),
            JAVA_INT.withName("maxY"),
            JAVA_INT.withName("innerY"),
            JAVA_FLOAT.withName("yScale"),
            RuntimeHelper.POINTER.withName("verticalRotation"),
            JAVA_FLOAT.withName("minVerRot"),
            JAVA_FLOAT.withName("maxVerRot"),
            RuntimeHelper.POINTER.withName("distanceFactor"),
            JAVA_FLOAT.withName("minDistance"),
            JAVA_FLOAT.withName("maxDistance"),
            RuntimeHelper.POINTER.withName("thickness"),
            JAVA_FLOAT.withName("minThickness"),
            JAVA_FLOAT.withName("maxThickness"),
            JAVA_FLOAT.withName("plateauThickness"),
            JAVA_INT.withName("widthSmoothness"),
            RuntimeHelper.POINTER.withName("horizontalRadiusFactor"),
            JAVA_FLOAT.withName("minHorRadius"),
            JAVA_FLOAT.withName("maxHorRadius"),
            JAVA_FLOAT.withName("verticalRadiusDefaultFactor"),
            JAVA_FLOAT.withName("verticalRadiusCenterFactor")
        ).withName("CanyonCarverConfig")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "carveCanyon",
        constants$86.const$5
    );
}


