// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final VarHandle const$0 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("h2"));
    static final VarHandle const$1 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("a"));
    static final VarHandle const$2 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("b"));
    static final VarHandle const$3 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("c"));
    static final VarHandle const$4 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("amplitude"));
    static final VarHandle const$5 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("lacunarity"));
}


