// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct DoublePerlinNoise {
 *     double amplitude;
 *     OctaveNoise octA;
 *     OctaveNoise octB;
 * };
 * }
 */
public class DoublePerlinNoise {

    public static MemoryLayout $LAYOUT() {
        return constants$6.const$5;
    }
    public static VarHandle amplitude$VH() {
        return constants$7.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double amplitude;
     * }
     */
    public static double amplitude(MemorySegment seg) {
        return (double)constants$7.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double amplitude;
     * }
     */
    public static void amplitude(MemorySegment seg, double x) {
        constants$7.const$0.set(seg, x);
    }
    public static double amplitudeAtIndex(MemorySegment seg, long index) {
        return (double)constants$7.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void amplitudeAtIndex(MemorySegment seg, long index, double x) {
        constants$7.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment octA(MemorySegment seg) {
        return seg.asSlice(8, 16);
    }
    public static MemorySegment octB(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}