// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct EnchantInstance {
 *     int enchantment;
 *     int level;
 * };
 * }
 */
public class EnchantInstance {

    public static MemoryLayout $LAYOUT() {
        return constants$101.const$4;
    }
    public static VarHandle enchantment$VH() {
        return constants$101.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int enchantment;
     * }
     */
    public static int enchantment(MemorySegment seg) {
        return (int)constants$101.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int enchantment;
     * }
     */
    public static void enchantment(MemorySegment seg, int x) {
        constants$101.const$5.set(seg, x);
    }
    public static int enchantmentAtIndex(MemorySegment seg, long index) {
        return (int)constants$101.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void enchantmentAtIndex(MemorySegment seg, long index, int x) {
        constants$101.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle level$VH() {
        return constants$102.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int level;
     * }
     */
    public static int level(MemorySegment seg) {
        return (int)constants$102.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int level;
     * }
     */
    public static void level(MemorySegment seg, int x) {
        constants$102.const$0.set(seg, x);
    }
    public static int levelAtIndex(MemorySegment seg, long index) {
        return (int)constants$102.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void levelAtIndex(MemorySegment seg, long index, int x) {
        constants$102.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}