// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct EndNoise {
 *     PerlinNoise perlin;
 *     int mc;
 * };
 * }
 */
public class EndNoise {

    public static MemoryLayout $LAYOUT() {
        return constants$24.const$3;
    }
    public static MemorySegment perlin(MemorySegment seg) {
        return seg.asSlice(0, 320);
    }
    public static VarHandle mc$VH() {
        return constants$24.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static int mc(MemorySegment seg) {
        return (int)constants$24.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static void mc(MemorySegment seg, int x) {
        constants$24.const$4.set(seg, x);
    }
    public static int mcAtIndex(MemorySegment seg, long index) {
        return (int)constants$24.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void mcAtIndex(MemorySegment seg, long index, int x) {
        constants$24.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}