// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct FixSpline {
 *     int len;
 *     float val;
 * };
 * }
 */
public class FixSpline {

    public static MemoryLayout $LAYOUT() {
        return constants$26.const$5;
    }
    public static VarHandle len$VH() {
        return constants$27.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int len;
     * }
     */
    public static int len(MemorySegment seg) {
        return (int)constants$27.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int len;
     * }
     */
    public static void len(MemorySegment seg, int x) {
        constants$27.const$0.set(seg, x);
    }
    public static int lenAtIndex(MemorySegment seg, long index) {
        return (int)constants$27.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void lenAtIndex(MemorySegment seg, long index, int x) {
        constants$27.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle val$VH() {
        return constants$27.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float val;
     * }
     */
    public static float val(MemorySegment seg) {
        return (float)constants$27.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float val;
     * }
     */
    public static void val(MemorySegment seg, float x) {
        constants$27.const$1.set(seg, x);
    }
    public static float valAtIndex(MemorySegment seg, long index) {
        return (float)constants$27.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void valAtIndex(MemorySegment seg, long index, float x) {
        constants$27.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}