// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Generator {
 *     int mc;
 *     int dim;
 *     uint32_t flags;
 *     uint64_t seed;
 *     uint64_t sha;
 *     union {
 *         struct {
 *             LayerStack ls;
 *             Layer xlayer[5];
 *             Layer* entry;
 *         };
 *         struct {
 *             BiomeNoise bn;
 *         };
 *         struct {
 *             BiomeNoiseBeta bnb;
 *         };
 *     };
 *     NetherNoise nn;
 *     EndNoise en;
 * };
 * }
 */
public class Generator {

    public static MemoryLayout $LAYOUT() {
        return constants$44.const$0;
    }
    public static VarHandle mc$VH() {
        return constants$44.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static int mc(MemorySegment seg) {
        return (int)constants$44.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static void mc(MemorySegment seg, int x) {
        constants$44.const$1.set(seg, x);
    }
    public static int mcAtIndex(MemorySegment seg, long index) {
        return (int)constants$44.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void mcAtIndex(MemorySegment seg, long index, int x) {
        constants$44.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dim$VH() {
        return constants$44.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int dim;
     * }
     */
    public static int dim(MemorySegment seg) {
        return (int)constants$44.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int dim;
     * }
     */
    public static void dim(MemorySegment seg, int x) {
        constants$44.const$2.set(seg, x);
    }
    public static int dimAtIndex(MemorySegment seg, long index) {
        return (int)constants$44.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void dimAtIndex(MemorySegment seg, long index, int x) {
        constants$44.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle flags$VH() {
        return constants$44.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t flags;
     * }
     */
    public static int flags(MemorySegment seg) {
        return (int)constants$44.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t flags;
     * }
     */
    public static void flags(MemorySegment seg, int x) {
        constants$44.const$3.set(seg, x);
    }
    public static int flagsAtIndex(MemorySegment seg, long index) {
        return (int)constants$44.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void flagsAtIndex(MemorySegment seg, long index, int x) {
        constants$44.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle seed$VH() {
        return constants$44.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t seed;
     * }
     */
    public static long seed(MemorySegment seg) {
        return (long)constants$44.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t seed;
     * }
     */
    public static void seed(MemorySegment seg, long x) {
        constants$44.const$4.set(seg, x);
    }
    public static long seedAtIndex(MemorySegment seg, long index) {
        return (long)constants$44.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void seedAtIndex(MemorySegment seg, long index, long x) {
        constants$44.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sha$VH() {
        return constants$44.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t sha;
     * }
     */
    public static long sha(MemorySegment seg) {
        return (long)constants$44.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t sha;
     * }
     */
    public static void sha(MemorySegment seg, long x) {
        constants$44.const$5.set(seg, x);
    }
    public static long shaAtIndex(MemorySegment seg, long index) {
        return (long)constants$44.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void shaAtIndex(MemorySegment seg, long index, long x) {
        constants$44.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment ls(MemorySegment seg) {
        return seg.asSlice(32, 4752);
    }
    public static MemorySegment xlayer(MemorySegment seg) {
        return seg.asSlice(4784, 360);
    }
    public static VarHandle entry$VH() {
        return constants$45.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* entry;
     * }
     */
    public static MemorySegment entry(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$45.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* entry;
     * }
     */
    public static void entry(MemorySegment seg, MemorySegment x) {
        constants$45.const$0.set(seg, x);
    }
    public static MemorySegment entryAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$45.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void entryAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$45.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment bn(MemorySegment seg) {
        return seg.asSlice(32, 24592);
    }
    public static MemorySegment bnb(MemorySegment seg) {
        return seg.asSlice(32, 3256);
    }
    public static MemorySegment nn(MemorySegment seg) {
        return seg.asSlice(24624, 2640);
    }
    public static MemorySegment en(MemorySegment seg) {
        return seg.asSlice(27264, 328);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}