// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*getParaDescent$func)(void*,int,int,double);
 * }
 */
public interface getParaDescent$func {

    int apply(java.lang.foreign.MemorySegment _x0, int _x1, int _x2, double _x3);
    static MemorySegment allocate(getParaDescent$func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$94.const$5, fi, constants$94.const$4, scope);
    }
    static getParaDescent$func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, int __x1, int __x2, double __x3) -> {
            try {
                return (int)constants$95.const$0.invokeExact(symbol, __x0, __x1, __x2, __x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


