// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct ItemStack {
 *     int item;
 *     int count;
 *     int enchantment_count;
 *     EnchantInstance enchantments[16];
 * };
 * }
 */
public class ItemStack {

    public static MemoryLayout $LAYOUT() {
        return constants$102.const$1;
    }
    public static VarHandle item$VH() {
        return constants$102.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int item;
     * }
     */
    public static int item(MemorySegment seg) {
        return (int)constants$102.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int item;
     * }
     */
    public static void item(MemorySegment seg, int x) {
        constants$102.const$2.set(seg, x);
    }
    public static int itemAtIndex(MemorySegment seg, long index) {
        return (int)constants$102.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void itemAtIndex(MemorySegment seg, long index, int x) {
        constants$102.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle count$VH() {
        return constants$102.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int count;
     * }
     */
    public static int count(MemorySegment seg) {
        return (int)constants$102.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int count;
     * }
     */
    public static void count(MemorySegment seg, int x) {
        constants$102.const$3.set(seg, x);
    }
    public static int countAtIndex(MemorySegment seg, long index) {
        return (int)constants$102.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void countAtIndex(MemorySegment seg, long index, int x) {
        constants$102.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enchantment_count$VH() {
        return constants$102.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int enchantment_count;
     * }
     */
    public static int enchantment_count(MemorySegment seg) {
        return (int)constants$102.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int enchantment_count;
     * }
     */
    public static void enchantment_count(MemorySegment seg, int x) {
        constants$102.const$4.set(seg, x);
    }
    public static int enchantment_countAtIndex(MemorySegment seg, long index) {
        return (int)constants$102.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void enchantment_countAtIndex(MemorySegment seg, long index, int x) {
        constants$102.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment enchantments(MemorySegment seg) {
        return seg.asSlice(12, 128);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}