// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Layer {
 *     mapfunc_t* getMap;
 *     int8_t mc;
 *     int8_t zoom;
 *     int8_t edge;
 *     int scale;
 *     uint64_t layerSalt;
 *     uint64_t startSalt;
 *     uint64_t startSeed;
 *     void* noise;
 *     void* data;
 *     Layer* p;
 *     Layer* p2;
 * };
 * }
 */
public class Layer {

    public static MemoryLayout $LAYOUT() {
        return constants$14.const$0;
    }
    public static VarHandle getMap$VH() {
        return constants$14.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * mapfunc_t* getMap;
     * }
     */
    public static MemorySegment getMap(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$14.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * mapfunc_t* getMap;
     * }
     */
    public static void getMap(MemorySegment seg, MemorySegment x) {
        constants$14.const$1.set(seg, x);
    }
    public static MemorySegment getMapAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$14.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void getMapAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$14.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mc$VH() {
        return constants$14.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t mc;
     * }
     */
    public static byte mc(MemorySegment seg) {
        return (byte)constants$14.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t mc;
     * }
     */
    public static void mc(MemorySegment seg, byte x) {
        constants$14.const$2.set(seg, x);
    }
    public static byte mcAtIndex(MemorySegment seg, long index) {
        return (byte)constants$14.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void mcAtIndex(MemorySegment seg, long index, byte x) {
        constants$14.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle zoom$VH() {
        return constants$14.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t zoom;
     * }
     */
    public static byte zoom(MemorySegment seg) {
        return (byte)constants$14.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t zoom;
     * }
     */
    public static void zoom(MemorySegment seg, byte x) {
        constants$14.const$3.set(seg, x);
    }
    public static byte zoomAtIndex(MemorySegment seg, long index) {
        return (byte)constants$14.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void zoomAtIndex(MemorySegment seg, long index, byte x) {
        constants$14.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle edge$VH() {
        return constants$14.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t edge;
     * }
     */
    public static byte edge(MemorySegment seg) {
        return (byte)constants$14.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t edge;
     * }
     */
    public static void edge(MemorySegment seg, byte x) {
        constants$14.const$4.set(seg, x);
    }
    public static byte edgeAtIndex(MemorySegment seg, long index) {
        return (byte)constants$14.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void edgeAtIndex(MemorySegment seg, long index, byte x) {
        constants$14.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle scale$VH() {
        return constants$14.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int scale;
     * }
     */
    public static int scale(MemorySegment seg) {
        return (int)constants$14.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int scale;
     * }
     */
    public static void scale(MemorySegment seg, int x) {
        constants$14.const$5.set(seg, x);
    }
    public static int scaleAtIndex(MemorySegment seg, long index) {
        return (int)constants$14.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void scaleAtIndex(MemorySegment seg, long index, int x) {
        constants$14.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle layerSalt$VH() {
        return constants$15.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t layerSalt;
     * }
     */
    public static long layerSalt(MemorySegment seg) {
        return (long)constants$15.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t layerSalt;
     * }
     */
    public static void layerSalt(MemorySegment seg, long x) {
        constants$15.const$0.set(seg, x);
    }
    public static long layerSaltAtIndex(MemorySegment seg, long index) {
        return (long)constants$15.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void layerSaltAtIndex(MemorySegment seg, long index, long x) {
        constants$15.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle startSalt$VH() {
        return constants$15.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t startSalt;
     * }
     */
    public static long startSalt(MemorySegment seg) {
        return (long)constants$15.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t startSalt;
     * }
     */
    public static void startSalt(MemorySegment seg, long x) {
        constants$15.const$1.set(seg, x);
    }
    public static long startSaltAtIndex(MemorySegment seg, long index) {
        return (long)constants$15.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void startSaltAtIndex(MemorySegment seg, long index, long x) {
        constants$15.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle startSeed$VH() {
        return constants$15.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t startSeed;
     * }
     */
    public static long startSeed(MemorySegment seg) {
        return (long)constants$15.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t startSeed;
     * }
     */
    public static void startSeed(MemorySegment seg, long x) {
        constants$15.const$2.set(seg, x);
    }
    public static long startSeedAtIndex(MemorySegment seg, long index) {
        return (long)constants$15.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void startSeedAtIndex(MemorySegment seg, long index, long x) {
        constants$15.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle noise$VH() {
        return constants$15.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* noise;
     * }
     */
    public static MemorySegment noise(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$15.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* noise;
     * }
     */
    public static void noise(MemorySegment seg, MemorySegment x) {
        constants$15.const$3.set(seg, x);
    }
    public static MemorySegment noiseAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$15.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void noiseAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$15.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle data$VH() {
        return constants$15.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static MemorySegment data(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$15.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static void data(MemorySegment seg, MemorySegment x) {
        constants$15.const$4.set(seg, x);
    }
    public static MemorySegment dataAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$15.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void dataAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$15.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle p$VH() {
        return constants$15.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* p;
     * }
     */
    public static MemorySegment p(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$15.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* p;
     * }
     */
    public static void p(MemorySegment seg, MemorySegment x) {
        constants$15.const$5.set(seg, x);
    }
    public static MemorySegment pAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$15.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void pAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$15.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle p2$VH() {
        return constants$16.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* p2;
     * }
     */
    public static MemorySegment p2(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$16.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* p2;
     * }
     */
    public static void p2(MemorySegment seg, MemorySegment x) {
        constants$16.const$0.set(seg, x);
    }
    public static MemorySegment p2AtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$16.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void p2AtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$16.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}