// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct LayerStack {
 *     Layer layers[61];
 *     Layer* entry_1;
 *     Layer* entry_4;
 *     Layer* entry_16;
 *     Layer* entry_64;
 *     Layer* entry_256;
 *     PerlinNoise oceanRnd;
 * };
 * }
 */
public class LayerStack {

    public static MemoryLayout $LAYOUT() {
        return constants$16.const$1;
    }
    public static MemorySegment layers(MemorySegment seg) {
        return seg.asSlice(0, 4392);
    }
    public static VarHandle entry_1$VH() {
        return constants$16.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* entry_1;
     * }
     */
    public static MemorySegment entry_1(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$16.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* entry_1;
     * }
     */
    public static void entry_1(MemorySegment seg, MemorySegment x) {
        constants$16.const$2.set(seg, x);
    }
    public static MemorySegment entry_1AtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$16.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_1AtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$16.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_4$VH() {
        return constants$16.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* entry_4;
     * }
     */
    public static MemorySegment entry_4(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$16.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* entry_4;
     * }
     */
    public static void entry_4(MemorySegment seg, MemorySegment x) {
        constants$16.const$3.set(seg, x);
    }
    public static MemorySegment entry_4AtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$16.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_4AtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$16.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_16$VH() {
        return constants$16.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* entry_16;
     * }
     */
    public static MemorySegment entry_16(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$16.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* entry_16;
     * }
     */
    public static void entry_16(MemorySegment seg, MemorySegment x) {
        constants$16.const$4.set(seg, x);
    }
    public static MemorySegment entry_16AtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$16.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_16AtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$16.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_64$VH() {
        return constants$16.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* entry_64;
     * }
     */
    public static MemorySegment entry_64(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$16.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* entry_64;
     * }
     */
    public static void entry_64(MemorySegment seg, MemorySegment x) {
        constants$16.const$5.set(seg, x);
    }
    public static MemorySegment entry_64AtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$16.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_64AtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$16.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_256$VH() {
        return constants$17.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Layer* entry_256;
     * }
     */
    public static MemorySegment entry_256(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$17.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Layer* entry_256;
     * }
     */
    public static void entry_256(MemorySegment seg, MemorySegment x) {
        constants$17.const$0.set(seg, x);
    }
    public static MemorySegment entry_256AtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$17.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_256AtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$17.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment oceanRnd(MemorySegment seg) {
        return seg.asSlice(4432, 320);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}