// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct LootTableContext {
 *     int version;
 *     int item_count;
 *     char** item_names;
 *     int* global_item_ids;
 *     int pool_count;
 *     LootPool* loot_pools;
 *     int unresolved_subtable_count;
 *     char* unresolved_subtable_names[8];
 *     int subtable_count;
 *     int* subtable_pool_offset;
 *     int* subtable_pool_count;
 *     uint64_t prng_state;
 *     int generated_item_count;
 *     ItemStack generated_items[27];
 * };
 * }
 */
public class LootTableContext {

    public static MemoryLayout $LAYOUT() {
        return constants$108.const$4;
    }
    public static VarHandle version$VH() {
        return constants$108.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int version;
     * }
     */
    public static int version(MemorySegment seg) {
        return (int)constants$108.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int version;
     * }
     */
    public static void version(MemorySegment seg, int x) {
        constants$108.const$5.set(seg, x);
    }
    public static int versionAtIndex(MemorySegment seg, long index) {
        return (int)constants$108.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void versionAtIndex(MemorySegment seg, long index, int x) {
        constants$108.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle item_count$VH() {
        return constants$109.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int item_count;
     * }
     */
    public static int item_count(MemorySegment seg) {
        return (int)constants$109.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int item_count;
     * }
     */
    public static void item_count(MemorySegment seg, int x) {
        constants$109.const$0.set(seg, x);
    }
    public static int item_countAtIndex(MemorySegment seg, long index) {
        return (int)constants$109.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void item_countAtIndex(MemorySegment seg, long index, int x) {
        constants$109.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle item_names$VH() {
        return constants$109.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char** item_names;
     * }
     */
    public static MemorySegment item_names(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$109.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char** item_names;
     * }
     */
    public static void item_names(MemorySegment seg, MemorySegment x) {
        constants$109.const$1.set(seg, x);
    }
    public static MemorySegment item_namesAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$109.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void item_namesAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$109.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle global_item_ids$VH() {
        return constants$109.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* global_item_ids;
     * }
     */
    public static MemorySegment global_item_ids(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$109.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* global_item_ids;
     * }
     */
    public static void global_item_ids(MemorySegment seg, MemorySegment x) {
        constants$109.const$2.set(seg, x);
    }
    public static MemorySegment global_item_idsAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$109.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void global_item_idsAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$109.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pool_count$VH() {
        return constants$109.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int pool_count;
     * }
     */
    public static int pool_count(MemorySegment seg) {
        return (int)constants$109.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int pool_count;
     * }
     */
    public static void pool_count(MemorySegment seg, int x) {
        constants$109.const$3.set(seg, x);
    }
    public static int pool_countAtIndex(MemorySegment seg, long index) {
        return (int)constants$109.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void pool_countAtIndex(MemorySegment seg, long index, int x) {
        constants$109.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle loot_pools$VH() {
        return constants$109.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LootPool* loot_pools;
     * }
     */
    public static MemorySegment loot_pools(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$109.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LootPool* loot_pools;
     * }
     */
    public static void loot_pools(MemorySegment seg, MemorySegment x) {
        constants$109.const$4.set(seg, x);
    }
    public static MemorySegment loot_poolsAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$109.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void loot_poolsAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$109.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle unresolved_subtable_count$VH() {
        return constants$109.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int unresolved_subtable_count;
     * }
     */
    public static int unresolved_subtable_count(MemorySegment seg) {
        return (int)constants$109.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int unresolved_subtable_count;
     * }
     */
    public static void unresolved_subtable_count(MemorySegment seg, int x) {
        constants$109.const$5.set(seg, x);
    }
    public static int unresolved_subtable_countAtIndex(MemorySegment seg, long index) {
        return (int)constants$109.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void unresolved_subtable_countAtIndex(MemorySegment seg, long index, int x) {
        constants$109.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment unresolved_subtable_names(MemorySegment seg) {
        return seg.asSlice(48, 64);
    }
    public static VarHandle subtable_count$VH() {
        return constants$110.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int subtable_count;
     * }
     */
    public static int subtable_count(MemorySegment seg) {
        return (int)constants$110.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int subtable_count;
     * }
     */
    public static void subtable_count(MemorySegment seg, int x) {
        constants$110.const$0.set(seg, x);
    }
    public static int subtable_countAtIndex(MemorySegment seg, long index) {
        return (int)constants$110.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void subtable_countAtIndex(MemorySegment seg, long index, int x) {
        constants$110.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle subtable_pool_offset$VH() {
        return constants$110.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* subtable_pool_offset;
     * }
     */
    public static MemorySegment subtable_pool_offset(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$110.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* subtable_pool_offset;
     * }
     */
    public static void subtable_pool_offset(MemorySegment seg, MemorySegment x) {
        constants$110.const$1.set(seg, x);
    }
    public static MemorySegment subtable_pool_offsetAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$110.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void subtable_pool_offsetAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$110.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle subtable_pool_count$VH() {
        return constants$110.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* subtable_pool_count;
     * }
     */
    public static MemorySegment subtable_pool_count(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$110.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* subtable_pool_count;
     * }
     */
    public static void subtable_pool_count(MemorySegment seg, MemorySegment x) {
        constants$110.const$2.set(seg, x);
    }
    public static MemorySegment subtable_pool_countAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$110.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void subtable_pool_countAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$110.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle prng_state$VH() {
        return constants$110.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t prng_state;
     * }
     */
    public static long prng_state(MemorySegment seg) {
        return (long)constants$110.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t prng_state;
     * }
     */
    public static void prng_state(MemorySegment seg, long x) {
        constants$110.const$3.set(seg, x);
    }
    public static long prng_stateAtIndex(MemorySegment seg, long index) {
        return (long)constants$110.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void prng_stateAtIndex(MemorySegment seg, long index, long x) {
        constants$110.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle generated_item_count$VH() {
        return constants$110.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int generated_item_count;
     * }
     */
    public static int generated_item_count(MemorySegment seg) {
        return (int)constants$110.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int generated_item_count;
     * }
     */
    public static void generated_item_count(MemorySegment seg, int x) {
        constants$110.const$4.set(seg, x);
    }
    public static int generated_item_countAtIndex(MemorySegment seg, long index) {
        return (int)constants$110.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void generated_item_countAtIndex(MemorySegment seg, long index, int x) {
        constants$110.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment generated_items(MemorySegment seg) {
        return seg.asSlice(148, 3780);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}