// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct LootPool {
 *     int min_rolls;
 *     int max_rolls;
 *     RollCountFunction roll_count_function;
 *     int total_weight;
 *     int* precomputed_loot;
 *     int entry_count;
 *     int* entry_to_item;
 *     int* entry_functions_index;
 *     int* entry_functions_count;
 *     LootFunction* loot_functions;
 * };
 * }
 */
public class LootPool {

    public static MemoryLayout $LAYOUT() {
        return constants$106.const$5;
    }
    public static VarHandle min_rolls$VH() {
        return constants$107.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int min_rolls;
     * }
     */
    public static int min_rolls(MemorySegment seg) {
        return (int)constants$107.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int min_rolls;
     * }
     */
    public static void min_rolls(MemorySegment seg, int x) {
        constants$107.const$0.set(seg, x);
    }
    public static int min_rollsAtIndex(MemorySegment seg, long index) {
        return (int)constants$107.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void min_rollsAtIndex(MemorySegment seg, long index, int x) {
        constants$107.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle max_rolls$VH() {
        return constants$107.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int max_rolls;
     * }
     */
    public static int max_rolls(MemorySegment seg) {
        return (int)constants$107.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int max_rolls;
     * }
     */
    public static void max_rolls(MemorySegment seg, int x) {
        constants$107.const$1.set(seg, x);
    }
    public static int max_rollsAtIndex(MemorySegment seg, long index) {
        return (int)constants$107.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void max_rollsAtIndex(MemorySegment seg, long index, int x) {
        constants$107.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle roll_count_function$VH() {
        return constants$107.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * RollCountFunction roll_count_function;
     * }
     */
    public static MemorySegment roll_count_function(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$107.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * RollCountFunction roll_count_function;
     * }
     */
    public static void roll_count_function(MemorySegment seg, MemorySegment x) {
        constants$107.const$2.set(seg, x);
    }
    public static MemorySegment roll_count_functionAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$107.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void roll_count_functionAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$107.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static RollCountFunction roll_count_function(MemorySegment segment, Arena scope) {
        return RollCountFunction.ofAddress(roll_count_function(segment), scope);
    }
    public static VarHandle total_weight$VH() {
        return constants$107.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int total_weight;
     * }
     */
    public static int total_weight(MemorySegment seg) {
        return (int)constants$107.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int total_weight;
     * }
     */
    public static void total_weight(MemorySegment seg, int x) {
        constants$107.const$3.set(seg, x);
    }
    public static int total_weightAtIndex(MemorySegment seg, long index) {
        return (int)constants$107.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void total_weightAtIndex(MemorySegment seg, long index, int x) {
        constants$107.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle precomputed_loot$VH() {
        return constants$107.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* precomputed_loot;
     * }
     */
    public static MemorySegment precomputed_loot(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$107.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* precomputed_loot;
     * }
     */
    public static void precomputed_loot(MemorySegment seg, MemorySegment x) {
        constants$107.const$4.set(seg, x);
    }
    public static MemorySegment precomputed_lootAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$107.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void precomputed_lootAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$107.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_count$VH() {
        return constants$107.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int entry_count;
     * }
     */
    public static int entry_count(MemorySegment seg) {
        return (int)constants$107.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int entry_count;
     * }
     */
    public static void entry_count(MemorySegment seg, int x) {
        constants$107.const$5.set(seg, x);
    }
    public static int entry_countAtIndex(MemorySegment seg, long index) {
        return (int)constants$107.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_countAtIndex(MemorySegment seg, long index, int x) {
        constants$107.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_to_item$VH() {
        return constants$108.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* entry_to_item;
     * }
     */
    public static MemorySegment entry_to_item(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$108.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* entry_to_item;
     * }
     */
    public static void entry_to_item(MemorySegment seg, MemorySegment x) {
        constants$108.const$0.set(seg, x);
    }
    public static MemorySegment entry_to_itemAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$108.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_to_itemAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$108.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_functions_index$VH() {
        return constants$108.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* entry_functions_index;
     * }
     */
    public static MemorySegment entry_functions_index(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$108.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* entry_functions_index;
     * }
     */
    public static void entry_functions_index(MemorySegment seg, MemorySegment x) {
        constants$108.const$1.set(seg, x);
    }
    public static MemorySegment entry_functions_indexAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$108.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_functions_indexAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$108.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle entry_functions_count$VH() {
        return constants$108.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* entry_functions_count;
     * }
     */
    public static MemorySegment entry_functions_count(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$108.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* entry_functions_count;
     * }
     */
    public static void entry_functions_count(MemorySegment seg, MemorySegment x) {
        constants$108.const$2.set(seg, x);
    }
    public static MemorySegment entry_functions_countAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$108.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void entry_functions_countAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$108.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle loot_functions$VH() {
        return constants$108.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LootFunction* loot_functions;
     * }
     */
    public static MemorySegment loot_functions(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$108.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LootFunction* loot_functions;
     * }
     */
    public static void loot_functions(MemorySegment seg, MemorySegment x) {
        constants$108.const$3.set(seg, x);
    }
    public static MemorySegment loot_functionsAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$108.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void loot_functionsAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$108.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}