// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct LootTableOutput {
 *     ItemStack natural_loot[27];
 *     ItemStack indexed_loot[27];
 *     int aggregated_loot[64];
 * };
 * }
 */
public class LootTableOutput {

    public static MemoryLayout $LAYOUT() {
        return constants$110.const$5;
    }
    public static MemorySegment natural_loot(MemorySegment seg) {
        return seg.asSlice(0, 3780);
    }
    public static MemorySegment indexed_loot(MemorySegment seg) {
        return seg.asSlice(3780, 3780);
    }
    public static MemorySegment aggregated_loot(MemorySegment seg) {
        return seg.asSlice(7560, 256);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}