// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct LootFunction {
 *     void (*fun)(uint64_t*,ItemStack*,void*);
 *     void* params;
 *     int params_int[2];
 *     int* varparams_int;
 *     int** varparams_int_arr;
 *     int varparams_int_arr_size;
 * };
 * }
 */
public class LootFunction {

    public static MemoryLayout $LAYOUT() {
        return constants$103.const$0;
    }
    /**
     * {@snippet :
 * void (*fun)(uint64_t*,ItemStack*,void*);
     * }
     */
    public interface fun {

        void apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2);
        static MemorySegment allocate(fun fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$103.const$2, fi, constants$103.const$1, scope);
        }
        static fun ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2) -> {
                try {
                    constants$103.const$3.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle fun$VH() {
        return constants$103.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*fun)(uint64_t*,ItemStack*,void*);
     * }
     */
    public static MemorySegment fun(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$103.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*fun)(uint64_t*,ItemStack*,void*);
     * }
     */
    public static void fun(MemorySegment seg, MemorySegment x) {
        constants$103.const$4.set(seg, x);
    }
    public static MemorySegment funAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$103.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void funAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$103.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static fun fun(MemorySegment segment, Arena scope) {
        return fun.ofAddress(fun(segment), scope);
    }
    public static VarHandle params$VH() {
        return constants$103.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* params;
     * }
     */
    public static MemorySegment params(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$103.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* params;
     * }
     */
    public static void params(MemorySegment seg, MemorySegment x) {
        constants$103.const$5.set(seg, x);
    }
    public static MemorySegment paramsAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$103.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void paramsAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$103.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment params_int(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static VarHandle varparams_int$VH() {
        return constants$104.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* varparams_int;
     * }
     */
    public static MemorySegment varparams_int(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$104.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* varparams_int;
     * }
     */
    public static void varparams_int(MemorySegment seg, MemorySegment x) {
        constants$104.const$0.set(seg, x);
    }
    public static MemorySegment varparams_intAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$104.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void varparams_intAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$104.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle varparams_int_arr$VH() {
        return constants$104.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int** varparams_int_arr;
     * }
     */
    public static MemorySegment varparams_int_arr(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$104.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int** varparams_int_arr;
     * }
     */
    public static void varparams_int_arr(MemorySegment seg, MemorySegment x) {
        constants$104.const$1.set(seg, x);
    }
    public static MemorySegment varparams_int_arrAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$104.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void varparams_int_arrAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$104.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle varparams_int_arr_size$VH() {
        return constants$104.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int varparams_int_arr_size;
     * }
     */
    public static int varparams_int_arr_size(MemorySegment seg) {
        return (int)constants$104.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int varparams_int_arr_size;
     * }
     */
    public static void varparams_int_arr_size(MemorySegment seg, int x) {
        constants$104.const$2.set(seg, x);
    }
    public static int varparams_int_arr_sizeAtIndex(MemorySegment seg, long index) {
        return (int)constants$104.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void varparams_int_arr_sizeAtIndex(MemorySegment seg, long index, int x) {
        constants$104.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}