// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*mapfunc_t)(struct Layer*,int*,int,int,int,int);
 * }
 */
public interface mapfunc_t {

    int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, int _x2, int _x3, int _x4, int _x5);
    static MemorySegment allocate(mapfunc_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$13.const$4, fi, constants$13.const$3, scope);
    }
    static mapfunc_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, int __x2, int __x3, int __x4, int __x5) -> {
            try {
                return (int)constants$13.const$5.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4, __x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


