// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*monteCarloBiomes$eval)(Generator*,int,int,int,int,void*);
 * }
 */
public interface monteCarloBiomes$eval {

    int apply(java.lang.foreign.MemorySegment _x0, int _x1, int _x2, int _x3, int _x4, java.lang.foreign.MemorySegment _x5);
    static MemorySegment allocate(monteCarloBiomes$eval fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$91.const$3, fi, constants$91.const$2, scope);
    }
    static monteCarloBiomes$eval ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, int __x1, int __x2, int __x3, int __x4, java.lang.foreign.MemorySegment __x5) -> {
            try {
                return (int)constants$91.const$4.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4, __x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


