// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct NetherNoise {
 *     DoublePerlinNoise temperature;
 *     DoublePerlinNoise humidity;
 *     PerlinNoise oct[8];
 * };
 * }
 */
public class NetherNoise {

    public static MemoryLayout $LAYOUT() {
        return constants$24.const$2;
    }
    public static MemorySegment temperature(MemorySegment seg) {
        return seg.asSlice(0, 40);
    }
    public static MemorySegment humidity(MemorySegment seg) {
        return seg.asSlice(40, 40);
    }
    public static MemorySegment oct(MemorySegment seg) {
        return seg.asSlice(80, 2560);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}