// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct OctaveNoise {
 *     int octcnt;
 *     PerlinNoise* octaves;
 * };
 * }
 */
public class OctaveNoise {

    public static MemoryLayout $LAYOUT() {
        return constants$6.const$2;
    }
    public static VarHandle octcnt$VH() {
        return constants$6.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int octcnt;
     * }
     */
    public static int octcnt(MemorySegment seg) {
        return (int)constants$6.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int octcnt;
     * }
     */
    public static void octcnt(MemorySegment seg, int x) {
        constants$6.const$3.set(seg, x);
    }
    public static int octcntAtIndex(MemorySegment seg, long index) {
        return (int)constants$6.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void octcntAtIndex(MemorySegment seg, long index, int x) {
        constants$6.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle octaves$VH() {
        return constants$6.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PerlinNoise* octaves;
     * }
     */
    public static MemorySegment octaves(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PerlinNoise* octaves;
     * }
     */
    public static void octaves(MemorySegment seg, MemorySegment x) {
        constants$6.const$4.set(seg, x);
    }
    public static MemorySegment octavesAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void octavesAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}