// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct OreConfig {
 *     int32_t index;
 *     int32_t step;
 *     int32_t size;
 *     int32_t repeatCount;
 *     int (*heightProvider)(RandomSource,int,int,int);
 *     int32_t h1;
 *     int32_t h2;
 *     int32_t h3;
 *     uint32_t oreType;
 *     uint32_t oreBlock;
 *     int8_t dim;
 *     uint8_t numReplaceBlocks;
 *     const uint32_t* replaceBlocks;
 *     float discardChanceOnAirExposure;
 * };
 * }
 */
public class OreConfig {

    public static MemoryLayout $LAYOUT() {
        return constants$68.const$0;
    }
    public static VarHandle index$VH() {
        return constants$68.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t index;
     * }
     */
    public static int index(MemorySegment seg) {
        return (int)constants$68.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t index;
     * }
     */
    public static void index(MemorySegment seg, int x) {
        constants$68.const$1.set(seg, x);
    }
    public static int indexAtIndex(MemorySegment seg, long index) {
        return (int)constants$68.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void indexAtIndex(MemorySegment seg, long index, int x) {
        constants$68.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle step$VH() {
        return constants$68.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t step;
     * }
     */
    public static int step(MemorySegment seg) {
        return (int)constants$68.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t step;
     * }
     */
    public static void step(MemorySegment seg, int x) {
        constants$68.const$2.set(seg, x);
    }
    public static int stepAtIndex(MemorySegment seg, long index) {
        return (int)constants$68.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void stepAtIndex(MemorySegment seg, long index, int x) {
        constants$68.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle size$VH() {
        return constants$68.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t size;
     * }
     */
    public static int size(MemorySegment seg) {
        return (int)constants$68.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t size;
     * }
     */
    public static void size(MemorySegment seg, int x) {
        constants$68.const$3.set(seg, x);
    }
    public static int sizeAtIndex(MemorySegment seg, long index) {
        return (int)constants$68.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void sizeAtIndex(MemorySegment seg, long index, int x) {
        constants$68.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle repeatCount$VH() {
        return constants$68.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t repeatCount;
     * }
     */
    public static int repeatCount(MemorySegment seg) {
        return (int)constants$68.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t repeatCount;
     * }
     */
    public static void repeatCount(MemorySegment seg, int x) {
        constants$68.const$4.set(seg, x);
    }
    public static int repeatCountAtIndex(MemorySegment seg, long index) {
        return (int)constants$68.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void repeatCountAtIndex(MemorySegment seg, long index, int x) {
        constants$68.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * int (*heightProvider)(RandomSource,int,int,int);
     * }
     */
    public interface heightProvider {

        int apply(java.lang.foreign.MemorySegment _x0, int _x1, int _x2, int _x3);
        static MemorySegment allocate(heightProvider fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$69.const$0, fi, constants$68.const$5, scope);
        }
        static heightProvider ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, int __x1, int __x2, int __x3) -> {
                try {
                    return (int)constants$69.const$1.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle heightProvider$VH() {
        return constants$69.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*heightProvider)(RandomSource,int,int,int);
     * }
     */
    public static MemorySegment heightProvider(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$69.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*heightProvider)(RandomSource,int,int,int);
     * }
     */
    public static void heightProvider(MemorySegment seg, MemorySegment x) {
        constants$69.const$2.set(seg, x);
    }
    public static MemorySegment heightProviderAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$69.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void heightProviderAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$69.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static heightProvider heightProvider(MemorySegment segment, Arena scope) {
        return heightProvider.ofAddress(heightProvider(segment), scope);
    }
    public static VarHandle h1$VH() {
        return constants$69.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t h1;
     * }
     */
    public static int h1(MemorySegment seg) {
        return (int)constants$69.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t h1;
     * }
     */
    public static void h1(MemorySegment seg, int x) {
        constants$69.const$3.set(seg, x);
    }
    public static int h1AtIndex(MemorySegment seg, long index) {
        return (int)constants$69.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void h1AtIndex(MemorySegment seg, long index, int x) {
        constants$69.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle h2$VH() {
        return constants$69.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t h2;
     * }
     */
    public static int h2(MemorySegment seg) {
        return (int)constants$69.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t h2;
     * }
     */
    public static void h2(MemorySegment seg, int x) {
        constants$69.const$4.set(seg, x);
    }
    public static int h2AtIndex(MemorySegment seg, long index) {
        return (int)constants$69.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void h2AtIndex(MemorySegment seg, long index, int x) {
        constants$69.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle h3$VH() {
        return constants$69.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t h3;
     * }
     */
    public static int h3(MemorySegment seg) {
        return (int)constants$69.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t h3;
     * }
     */
    public static void h3(MemorySegment seg, int x) {
        constants$69.const$5.set(seg, x);
    }
    public static int h3AtIndex(MemorySegment seg, long index) {
        return (int)constants$69.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void h3AtIndex(MemorySegment seg, long index, int x) {
        constants$69.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle oreType$VH() {
        return constants$70.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t oreType;
     * }
     */
    public static int oreType(MemorySegment seg) {
        return (int)constants$70.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t oreType;
     * }
     */
    public static void oreType(MemorySegment seg, int x) {
        constants$70.const$0.set(seg, x);
    }
    public static int oreTypeAtIndex(MemorySegment seg, long index) {
        return (int)constants$70.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void oreTypeAtIndex(MemorySegment seg, long index, int x) {
        constants$70.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle oreBlock$VH() {
        return constants$70.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t oreBlock;
     * }
     */
    public static int oreBlock(MemorySegment seg) {
        return (int)constants$70.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t oreBlock;
     * }
     */
    public static void oreBlock(MemorySegment seg, int x) {
        constants$70.const$1.set(seg, x);
    }
    public static int oreBlockAtIndex(MemorySegment seg, long index) {
        return (int)constants$70.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void oreBlockAtIndex(MemorySegment seg, long index, int x) {
        constants$70.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dim$VH() {
        return constants$70.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t dim;
     * }
     */
    public static byte dim(MemorySegment seg) {
        return (byte)constants$70.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t dim;
     * }
     */
    public static void dim(MemorySegment seg, byte x) {
        constants$70.const$2.set(seg, x);
    }
    public static byte dimAtIndex(MemorySegment seg, long index) {
        return (byte)constants$70.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void dimAtIndex(MemorySegment seg, long index, byte x) {
        constants$70.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle numReplaceBlocks$VH() {
        return constants$70.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t numReplaceBlocks;
     * }
     */
    public static byte numReplaceBlocks(MemorySegment seg) {
        return (byte)constants$70.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t numReplaceBlocks;
     * }
     */
    public static void numReplaceBlocks(MemorySegment seg, byte x) {
        constants$70.const$3.set(seg, x);
    }
    public static byte numReplaceBlocksAtIndex(MemorySegment seg, long index) {
        return (byte)constants$70.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void numReplaceBlocksAtIndex(MemorySegment seg, long index, byte x) {
        constants$70.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle replaceBlocks$VH() {
        return constants$70.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const uint32_t* replaceBlocks;
     * }
     */
    public static MemorySegment replaceBlocks(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$70.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const uint32_t* replaceBlocks;
     * }
     */
    public static void replaceBlocks(MemorySegment seg, MemorySegment x) {
        constants$70.const$4.set(seg, x);
    }
    public static MemorySegment replaceBlocksAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$70.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void replaceBlocksAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$70.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle discardChanceOnAirExposure$VH() {
        return constants$70.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float discardChanceOnAirExposure;
     * }
     */
    public static float discardChanceOnAirExposure(MemorySegment seg) {
        return (float)constants$70.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float discardChanceOnAirExposure;
     * }
     */
    public static void discardChanceOnAirExposure(MemorySegment seg, float x) {
        constants$70.const$5.set(seg, x);
    }
    public static float discardChanceOnAirExposureAtIndex(MemorySegment seg, long index) {
        return (float)constants$70.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void discardChanceOnAirExposureAtIndex(MemorySegment seg, long index, float x) {
        constants$70.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}