// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct OreVeinConfig {
 *     uint32_t oreBlock;
 *     uint32_t rawOreBlock;
 *     uint32_t fillerBlock;
 *     int32_t minY;
 *     int32_t maxY;
 * };
 * }
 */
public class OreVeinConfig {

    public static MemoryLayout $LAYOUT() {
        return constants$73.const$0;
    }
    public static VarHandle oreBlock$VH() {
        return constants$73.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t oreBlock;
     * }
     */
    public static int oreBlock(MemorySegment seg) {
        return (int)constants$73.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t oreBlock;
     * }
     */
    public static void oreBlock(MemorySegment seg, int x) {
        constants$73.const$1.set(seg, x);
    }
    public static int oreBlockAtIndex(MemorySegment seg, long index) {
        return (int)constants$73.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void oreBlockAtIndex(MemorySegment seg, long index, int x) {
        constants$73.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rawOreBlock$VH() {
        return constants$73.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t rawOreBlock;
     * }
     */
    public static int rawOreBlock(MemorySegment seg) {
        return (int)constants$73.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t rawOreBlock;
     * }
     */
    public static void rawOreBlock(MemorySegment seg, int x) {
        constants$73.const$2.set(seg, x);
    }
    public static int rawOreBlockAtIndex(MemorySegment seg, long index) {
        return (int)constants$73.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void rawOreBlockAtIndex(MemorySegment seg, long index, int x) {
        constants$73.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle fillerBlock$VH() {
        return constants$73.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t fillerBlock;
     * }
     */
    public static int fillerBlock(MemorySegment seg) {
        return (int)constants$73.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t fillerBlock;
     * }
     */
    public static void fillerBlock(MemorySegment seg, int x) {
        constants$73.const$3.set(seg, x);
    }
    public static int fillerBlockAtIndex(MemorySegment seg, long index) {
        return (int)constants$73.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void fillerBlockAtIndex(MemorySegment seg, long index, int x) {
        constants$73.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle minY$VH() {
        return constants$73.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t minY;
     * }
     */
    public static int minY(MemorySegment seg) {
        return (int)constants$73.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t minY;
     * }
     */
    public static void minY(MemorySegment seg, int x) {
        constants$73.const$4.set(seg, x);
    }
    public static int minYAtIndex(MemorySegment seg, long index) {
        return (int)constants$73.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void minYAtIndex(MemorySegment seg, long index, int x) {
        constants$73.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxY$VH() {
        return constants$73.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t maxY;
     * }
     */
    public static int maxY(MemorySegment seg) {
        return (int)constants$73.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t maxY;
     * }
     */
    public static void maxY(MemorySegment seg, int x) {
        constants$73.const$5.set(seg, x);
    }
    public static int maxYAtIndex(MemorySegment seg, long index) {
        return (int)constants$73.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void maxYAtIndex(MemorySegment seg, long index, int x) {
        constants$73.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}