// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct OreVeinParameters {
 *     PerlinNoise oct[8];
 *     DoublePerlinNoise oreVeininess;
 *     DoublePerlinNoise oreVeinA;
 *     DoublePerlinNoise oreVeinB;
 *     DoublePerlinNoise oreGap;
 *     Xoroshiro posRandom;
 * };
 * }
 */
public class OreVeinParameters {

    public static MemoryLayout $LAYOUT() {
        return constants$74.const$0;
    }
    public static MemorySegment oct(MemorySegment seg) {
        return seg.asSlice(0, 2560);
    }
    public static MemorySegment oreVeininess(MemorySegment seg) {
        return seg.asSlice(2560, 40);
    }
    public static MemorySegment oreVeinA(MemorySegment seg) {
        return seg.asSlice(2600, 40);
    }
    public static MemorySegment oreVeinB(MemorySegment seg) {
        return seg.asSlice(2640, 40);
    }
    public static MemorySegment oreGap(MemorySegment seg) {
        return seg.asSlice(2680, 40);
    }
    public static MemorySegment posRandom(MemorySegment seg) {
        return seg.asSlice(2720, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}