// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct PerlinNoise {
 *     uint8_t d[257];
 *     uint8_t h2;
 *     double a;
 *     double b;
 *     double c;
 *     double amplitude;
 *     double lacunarity;
 *     double d2;
 *     double t2;
 * };
 * }
 */
public class PerlinNoise {

    public static MemoryLayout $LAYOUT() {
        return constants$4.const$5;
    }
    public static MemorySegment d(MemorySegment seg) {
        return seg.asSlice(0, 257);
    }
    public static VarHandle h2$VH() {
        return constants$5.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t h2;
     * }
     */
    public static byte h2(MemorySegment seg) {
        return (byte)constants$5.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t h2;
     * }
     */
    public static void h2(MemorySegment seg, byte x) {
        constants$5.const$0.set(seg, x);
    }
    public static byte h2AtIndex(MemorySegment seg, long index) {
        return (byte)constants$5.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void h2AtIndex(MemorySegment seg, long index, byte x) {
        constants$5.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle a$VH() {
        return constants$5.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double a;
     * }
     */
    public static double a(MemorySegment seg) {
        return (double)constants$5.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double a;
     * }
     */
    public static void a(MemorySegment seg, double x) {
        constants$5.const$1.set(seg, x);
    }
    public static double aAtIndex(MemorySegment seg, long index) {
        return (double)constants$5.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void aAtIndex(MemorySegment seg, long index, double x) {
        constants$5.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle b$VH() {
        return constants$5.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double b;
     * }
     */
    public static double b(MemorySegment seg) {
        return (double)constants$5.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double b;
     * }
     */
    public static void b(MemorySegment seg, double x) {
        constants$5.const$2.set(seg, x);
    }
    public static double bAtIndex(MemorySegment seg, long index) {
        return (double)constants$5.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void bAtIndex(MemorySegment seg, long index, double x) {
        constants$5.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle c$VH() {
        return constants$5.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double c;
     * }
     */
    public static double c(MemorySegment seg) {
        return (double)constants$5.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double c;
     * }
     */
    public static void c(MemorySegment seg, double x) {
        constants$5.const$3.set(seg, x);
    }
    public static double cAtIndex(MemorySegment seg, long index) {
        return (double)constants$5.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void cAtIndex(MemorySegment seg, long index, double x) {
        constants$5.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle amplitude$VH() {
        return constants$5.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double amplitude;
     * }
     */
    public static double amplitude(MemorySegment seg) {
        return (double)constants$5.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double amplitude;
     * }
     */
    public static void amplitude(MemorySegment seg, double x) {
        constants$5.const$4.set(seg, x);
    }
    public static double amplitudeAtIndex(MemorySegment seg, long index) {
        return (double)constants$5.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void amplitudeAtIndex(MemorySegment seg, long index, double x) {
        constants$5.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle lacunarity$VH() {
        return constants$5.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double lacunarity;
     * }
     */
    public static double lacunarity(MemorySegment seg) {
        return (double)constants$5.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double lacunarity;
     * }
     */
    public static void lacunarity(MemorySegment seg, double x) {
        constants$5.const$5.set(seg, x);
    }
    public static double lacunarityAtIndex(MemorySegment seg, long index) {
        return (double)constants$5.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void lacunarityAtIndex(MemorySegment seg, long index, double x) {
        constants$5.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle d2$VH() {
        return constants$6.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double d2;
     * }
     */
    public static double d2(MemorySegment seg) {
        return (double)constants$6.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double d2;
     * }
     */
    public static void d2(MemorySegment seg, double x) {
        constants$6.const$0.set(seg, x);
    }
    public static double d2AtIndex(MemorySegment seg, long index) {
        return (double)constants$6.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void d2AtIndex(MemorySegment seg, long index, double x) {
        constants$6.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle t2$VH() {
        return constants$6.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double t2;
     * }
     */
    public static double t2(MemorySegment seg) {
        return (double)constants$6.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double t2;
     * }
     */
    public static void t2(MemorySegment seg, double x) {
        constants$6.const$1.set(seg, x);
    }
    public static double t2AtIndex(MemorySegment seg, long index) {
        return (double)constants$6.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void t2AtIndex(MemorySegment seg, long index, double x) {
        constants$6.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}