// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Piece {
 *     char* name;
 *     Pos3 pos;
 *     Pos3 bb0;
 *     Pos3 bb1;
 *     uint8_t rot;
 *     int8_t depth;
 *     int8_t type;
 *     int chestCount;
 *     Pos chestPoses[4];
 *     uint64_t lootSeeds[4];
 *     char* lootTables[4];
 *     Piece* next;
 * };
 * }
 */
public class Piece {

    public static MemoryLayout $LAYOUT() {
        return constants$57.const$2;
    }
    public static VarHandle name$VH() {
        return constants$57.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* name;
     * }
     */
    public static MemorySegment name(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$57.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* name;
     * }
     */
    public static void name(MemorySegment seg, MemorySegment x) {
        constants$57.const$3.set(seg, x);
    }
    public static MemorySegment nameAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$57.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void nameAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$57.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment pos(MemorySegment seg) {
        return seg.asSlice(8, 12);
    }
    public static MemorySegment bb0(MemorySegment seg) {
        return seg.asSlice(20, 12);
    }
    public static MemorySegment bb1(MemorySegment seg) {
        return seg.asSlice(32, 12);
    }
    public static VarHandle rot$VH() {
        return constants$57.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t rot;
     * }
     */
    public static byte rot(MemorySegment seg) {
        return (byte)constants$57.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t rot;
     * }
     */
    public static void rot(MemorySegment seg, byte x) {
        constants$57.const$4.set(seg, x);
    }
    public static byte rotAtIndex(MemorySegment seg, long index) {
        return (byte)constants$57.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void rotAtIndex(MemorySegment seg, long index, byte x) {
        constants$57.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle depth$VH() {
        return constants$57.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t depth;
     * }
     */
    public static byte depth(MemorySegment seg) {
        return (byte)constants$57.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t depth;
     * }
     */
    public static void depth(MemorySegment seg, byte x) {
        constants$57.const$5.set(seg, x);
    }
    public static byte depthAtIndex(MemorySegment seg, long index) {
        return (byte)constants$57.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void depthAtIndex(MemorySegment seg, long index, byte x) {
        constants$57.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle type$VH() {
        return constants$58.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t type;
     * }
     */
    public static byte type(MemorySegment seg) {
        return (byte)constants$58.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t type;
     * }
     */
    public static void type(MemorySegment seg, byte x) {
        constants$58.const$0.set(seg, x);
    }
    public static byte typeAtIndex(MemorySegment seg, long index) {
        return (byte)constants$58.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void typeAtIndex(MemorySegment seg, long index, byte x) {
        constants$58.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle chestCount$VH() {
        return constants$58.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int chestCount;
     * }
     */
    public static int chestCount(MemorySegment seg) {
        return (int)constants$58.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int chestCount;
     * }
     */
    public static void chestCount(MemorySegment seg, int x) {
        constants$58.const$1.set(seg, x);
    }
    public static int chestCountAtIndex(MemorySegment seg, long index) {
        return (int)constants$58.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void chestCountAtIndex(MemorySegment seg, long index, int x) {
        constants$58.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment chestPoses(MemorySegment seg) {
        return seg.asSlice(52, 32);
    }
    public static MemorySegment lootSeeds(MemorySegment seg) {
        return seg.asSlice(88, 32);
    }
    public static MemorySegment lootTables(MemorySegment seg) {
        return seg.asSlice(120, 32);
    }
    public static VarHandle next$VH() {
        return constants$58.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Piece* next;
     * }
     */
    public static MemorySegment next(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$58.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Piece* next;
     * }
     */
    public static void next(MemorySegment seg, MemorySegment x) {
        constants$58.const$2.set(seg, x);
    }
    public static MemorySegment nextAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$58.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void nextAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$58.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}