// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Pos3 {
 *     int x;
 *     int y;
 *     int z;
 * };
 * }
 */
public class Pos3 {

    public static MemoryLayout $LAYOUT() {
        return constants$50.const$4;
    }
    public static VarHandle x$VH() {
        return constants$50.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static int x(MemorySegment seg) {
        return (int)constants$50.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static void x(MemorySegment seg, int x) {
        constants$50.const$5.set(seg, x);
    }
    public static int xAtIndex(MemorySegment seg, long index) {
        return (int)constants$50.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void xAtIndex(MemorySegment seg, long index, int x) {
        constants$50.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle y$VH() {
        return constants$51.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static int y(MemorySegment seg) {
        return (int)constants$51.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static void y(MemorySegment seg, int x) {
        constants$51.const$0.set(seg, x);
    }
    public static int yAtIndex(MemorySegment seg, long index) {
        return (int)constants$51.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void yAtIndex(MemorySegment seg, long index, int x) {
        constants$51.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle z$VH() {
        return constants$51.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int z;
     * }
     */
    public static int z(MemorySegment seg) {
        return (int)constants$51.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int z;
     * }
     */
    public static void z(MemorySegment seg, int x) {
        constants$51.const$1.set(seg, x);
    }
    public static int zAtIndex(MemorySegment seg, long index) {
        return (int)constants$51.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void zAtIndex(MemorySegment seg, long index, int x) {
        constants$51.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}