// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Pos3List {
 *     Pos3* pos3s;
 *     int capacity;
 *     int size;
 * };
 * }
 */
public class Pos3List {

    public static MemoryLayout $LAYOUT() {
        return constants$51.const$2;
    }
    public static VarHandle pos3s$VH() {
        return constants$51.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Pos3* pos3s;
     * }
     */
    public static MemorySegment pos3s(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$51.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Pos3* pos3s;
     * }
     */
    public static void pos3s(MemorySegment seg, MemorySegment x) {
        constants$51.const$3.set(seg, x);
    }
    public static MemorySegment pos3sAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$51.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void pos3sAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$51.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle capacity$VH() {
        return constants$51.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int capacity;
     * }
     */
    public static int capacity(MemorySegment seg) {
        return (int)constants$51.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int capacity;
     * }
     */
    public static void capacity(MemorySegment seg, int x) {
        constants$51.const$4.set(seg, x);
    }
    public static int capacityAtIndex(MemorySegment seg, long index) {
        return (int)constants$51.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void capacityAtIndex(MemorySegment seg, long index, int x) {
        constants$51.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle size$VH() {
        return constants$51.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int size;
     * }
     */
    public static int size(MemorySegment seg) {
        return (int)constants$51.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int size;
     * }
     */
    public static void size(MemorySegment seg, int x) {
        constants$51.const$5.set(seg, x);
    }
    public static int sizeAtIndex(MemorySegment seg, long index) {
        return (int)constants$51.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void sizeAtIndex(MemorySegment seg, long index, int x) {
        constants$51.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}