// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct RandomSource {
 *     void* state;
 *     void (*setSeed)(void*,uint64_t);
 *     uint64_t (*nextLong)(void*);
 *     int (*nextInt)(void*,int);
 *     float (*nextFloat)(void*);
 *     double (*nextDouble)(void*);
 *     int (*nextIntBetween)(void*,int,int);
 * };
 * }
 */
public class RandomSource {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$3;
    }
    public static VarHandle state$VH() {
        return constants$0.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* state;
     * }
     */
    public static MemorySegment state(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$0.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* state;
     * }
     */
    public static void state(MemorySegment seg, MemorySegment x) {
        constants$0.const$4.set(seg, x);
    }
    public static MemorySegment stateAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$0.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void stateAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$0.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * void (*setSeed)(void*,uint64_t);
     * }
     */
    public interface setSeed {

        void apply(java.lang.foreign.MemorySegment _x0, long _x1);
        static MemorySegment allocate(setSeed fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$1.const$0, fi, constants$0.const$5, scope);
        }
        static setSeed ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1) -> {
                try {
                    constants$1.const$1.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle setSeed$VH() {
        return constants$1.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*setSeed)(void*,uint64_t);
     * }
     */
    public static MemorySegment setSeed(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$1.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*setSeed)(void*,uint64_t);
     * }
     */
    public static void setSeed(MemorySegment seg, MemorySegment x) {
        constants$1.const$2.set(seg, x);
    }
    public static MemorySegment setSeedAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$1.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void setSeedAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$1.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static setSeed setSeed(MemorySegment segment, Arena scope) {
        return setSeed.ofAddress(setSeed(segment), scope);
    }
    /**
     * {@snippet :
 * uint64_t (*nextLong)(void*);
     * }
     */
    public interface nextLong {

        long apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(nextLong fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$1.const$4, fi, constants$1.const$3, scope);
        }
        static nextLong ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (long)constants$1.const$5.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle nextLong$VH() {
        return constants$2.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t (*nextLong)(void*);
     * }
     */
    public static MemorySegment nextLong(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$2.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t (*nextLong)(void*);
     * }
     */
    public static void nextLong(MemorySegment seg, MemorySegment x) {
        constants$2.const$0.set(seg, x);
    }
    public static MemorySegment nextLongAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$2.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void nextLongAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$2.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static nextLong nextLong(MemorySegment segment, Arena scope) {
        return nextLong.ofAddress(nextLong(segment), scope);
    }
    /**
     * {@snippet :
 * int (*nextInt)(void*,int);
     * }
     */
    public interface nextInt {

        int apply(java.lang.foreign.MemorySegment _x0, int _x1);
        static MemorySegment allocate(nextInt fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$2.const$2, fi, constants$2.const$1, scope);
        }
        static nextInt ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, int __x1) -> {
                try {
                    return (int)constants$2.const$3.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle nextInt$VH() {
        return constants$2.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*nextInt)(void*,int);
     * }
     */
    public static MemorySegment nextInt(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$2.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*nextInt)(void*,int);
     * }
     */
    public static void nextInt(MemorySegment seg, MemorySegment x) {
        constants$2.const$4.set(seg, x);
    }
    public static MemorySegment nextIntAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$2.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void nextIntAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$2.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static nextInt nextInt(MemorySegment segment, Arena scope) {
        return nextInt.ofAddress(nextInt(segment), scope);
    }
    /**
     * {@snippet :
 * float (*nextFloat)(void*);
     * }
     */
    public interface nextFloat {

        float apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(nextFloat fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$3.const$0, fi, constants$2.const$5, scope);
        }
        static nextFloat ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (float)constants$3.const$1.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle nextFloat$VH() {
        return constants$3.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float (*nextFloat)(void*);
     * }
     */
    public static MemorySegment nextFloat(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$3.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float (*nextFloat)(void*);
     * }
     */
    public static void nextFloat(MemorySegment seg, MemorySegment x) {
        constants$3.const$2.set(seg, x);
    }
    public static MemorySegment nextFloatAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$3.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void nextFloatAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$3.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static nextFloat nextFloat(MemorySegment segment, Arena scope) {
        return nextFloat.ofAddress(nextFloat(segment), scope);
    }
    /**
     * {@snippet :
 * double (*nextDouble)(void*);
     * }
     */
    public interface nextDouble {

        double apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(nextDouble fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$3.const$4, fi, constants$3.const$3, scope);
        }
        static nextDouble ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (double)constants$3.const$5.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle nextDouble$VH() {
        return constants$4.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double (*nextDouble)(void*);
     * }
     */
    public static MemorySegment nextDouble(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$4.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double (*nextDouble)(void*);
     * }
     */
    public static void nextDouble(MemorySegment seg, MemorySegment x) {
        constants$4.const$0.set(seg, x);
    }
    public static MemorySegment nextDoubleAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$4.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void nextDoubleAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$4.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static nextDouble nextDouble(MemorySegment segment, Arena scope) {
        return nextDouble.ofAddress(nextDouble(segment), scope);
    }
    /**
     * {@snippet :
 * int (*nextIntBetween)(void*,int,int);
     * }
     */
    public interface nextIntBetween {

        int apply(java.lang.foreign.MemorySegment _x0, int _x1, int _x2);
        static MemorySegment allocate(nextIntBetween fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$4.const$2, fi, constants$4.const$1, scope);
        }
        static nextIntBetween ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, int __x1, int __x2) -> {
                try {
                    return (int)constants$4.const$3.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle nextIntBetween$VH() {
        return constants$4.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*nextIntBetween)(void*,int,int);
     * }
     */
    public static MemorySegment nextIntBetween(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$4.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*nextIntBetween)(void*,int,int);
     * }
     */
    public static void nextIntBetween(MemorySegment seg, MemorySegment x) {
        constants$4.const$4.set(seg, x);
    }
    public static MemorySegment nextIntBetweenAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$4.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void nextIntBetweenAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$4.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static nextIntBetween nextIntBetween(MemorySegment segment, Arena scope) {
        return nextIntBetween.ofAddress(nextIntBetween(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}