// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Range {
 *     int scale;
 *     int x;
 *     int z;
 *     int sx;
 *     int sz;
 *     int y;
 *     int sy;
 * };
 * }
 */
public class Range {

    public static MemoryLayout $LAYOUT() {
        return constants$23.const$0;
    }
    public static VarHandle scale$VH() {
        return constants$23.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int scale;
     * }
     */
    public static int scale(MemorySegment seg) {
        return (int)constants$23.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int scale;
     * }
     */
    public static void scale(MemorySegment seg, int x) {
        constants$23.const$1.set(seg, x);
    }
    public static int scaleAtIndex(MemorySegment seg, long index) {
        return (int)constants$23.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void scaleAtIndex(MemorySegment seg, long index, int x) {
        constants$23.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle x$VH() {
        return constants$23.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static int x(MemorySegment seg) {
        return (int)constants$23.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static void x(MemorySegment seg, int x) {
        constants$23.const$2.set(seg, x);
    }
    public static int xAtIndex(MemorySegment seg, long index) {
        return (int)constants$23.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void xAtIndex(MemorySegment seg, long index, int x) {
        constants$23.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle z$VH() {
        return constants$23.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int z;
     * }
     */
    public static int z(MemorySegment seg) {
        return (int)constants$23.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int z;
     * }
     */
    public static void z(MemorySegment seg, int x) {
        constants$23.const$3.set(seg, x);
    }
    public static int zAtIndex(MemorySegment seg, long index) {
        return (int)constants$23.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void zAtIndex(MemorySegment seg, long index, int x) {
        constants$23.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sx$VH() {
        return constants$23.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int sx;
     * }
     */
    public static int sx(MemorySegment seg) {
        return (int)constants$23.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int sx;
     * }
     */
    public static void sx(MemorySegment seg, int x) {
        constants$23.const$4.set(seg, x);
    }
    public static int sxAtIndex(MemorySegment seg, long index) {
        return (int)constants$23.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void sxAtIndex(MemorySegment seg, long index, int x) {
        constants$23.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sz$VH() {
        return constants$23.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int sz;
     * }
     */
    public static int sz(MemorySegment seg) {
        return (int)constants$23.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int sz;
     * }
     */
    public static void sz(MemorySegment seg, int x) {
        constants$23.const$5.set(seg, x);
    }
    public static int szAtIndex(MemorySegment seg, long index) {
        return (int)constants$23.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void szAtIndex(MemorySegment seg, long index, int x) {
        constants$23.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle y$VH() {
        return constants$24.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static int y(MemorySegment seg) {
        return (int)constants$24.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static void y(MemorySegment seg, int x) {
        constants$24.const$0.set(seg, x);
    }
    public static int yAtIndex(MemorySegment seg, long index) {
        return (int)constants$24.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void yAtIndex(MemorySegment seg, long index, int x) {
        constants$24.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sy$VH() {
        return constants$24.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int sy;
     * }
     */
    public static int sy(MemorySegment seg) {
        return (int)constants$24.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int sy;
     * }
     */
    public static void sy(MemorySegment seg, int x) {
        constants$24.const$1.set(seg, x);
    }
    public static int syAtIndex(MemorySegment seg, long index) {
        return (int)constants$24.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void syAtIndex(MemorySegment seg, long index, int x) {
        constants$24.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}