// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*RollCountFunction)(unsigned long long*,int,int);
 * }
 */
public interface RollCountFunction {

    int apply(java.lang.foreign.MemorySegment _x0, int _x1, int _x2);
    static MemorySegment allocate(RollCountFunction fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$102.const$5, fi, constants$4.const$1, scope);
    }
    static RollCountFunction ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, int __x1, int __x2) -> {
            try {
                return (int)constants$4.const$3.invokeExact(symbol, __x0, __x1, __x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


