// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SeaLevelColumnNoiseBeta {
 *     double contASample;
 *     double contBSample;
 *     double minSample[2];
 *     double maxSample[2];
 *     double mainSample[2];
 * };
 * }
 */
public class SeaLevelColumnNoiseBeta {

    public static MemoryLayout $LAYOUT() {
        return constants$25.const$5;
    }
    public static VarHandle contASample$VH() {
        return constants$26.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double contASample;
     * }
     */
    public static double contASample(MemorySegment seg) {
        return (double)constants$26.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double contASample;
     * }
     */
    public static void contASample(MemorySegment seg, double x) {
        constants$26.const$0.set(seg, x);
    }
    public static double contASampleAtIndex(MemorySegment seg, long index) {
        return (double)constants$26.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void contASampleAtIndex(MemorySegment seg, long index, double x) {
        constants$26.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle contBSample$VH() {
        return constants$26.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double contBSample;
     * }
     */
    public static double contBSample(MemorySegment seg) {
        return (double)constants$26.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double contBSample;
     * }
     */
    public static void contBSample(MemorySegment seg, double x) {
        constants$26.const$1.set(seg, x);
    }
    public static double contBSampleAtIndex(MemorySegment seg, long index) {
        return (double)constants$26.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void contBSampleAtIndex(MemorySegment seg, long index, double x) {
        constants$26.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment minSample(MemorySegment seg) {
        return seg.asSlice(16, 16);
    }
    public static MemorySegment maxSample(MemorySegment seg) {
        return seg.asSlice(32, 16);
    }
    public static MemorySegment mainSample(MemorySegment seg) {
        return seg.asSlice(48, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}