// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*searchAll48$check)(uint64_t,void*);
 * }
 */
public interface searchAll48$check {

    int apply(long _x0, java.lang.foreign.MemorySegment _x1);
    static MemorySegment allocate(searchAll48$check fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$100.const$0, fi, constants$99.const$5, scope);
    }
    static searchAll48$check ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long __x0, java.lang.foreign.MemorySegment __x1) -> {
            try {
                return (int)constants$100.const$1.invokeExact(symbol, __x0, __x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


