// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Spline {
 *     int len;
 *     int typ;
 *     float loc[12];
 *     float der[12];
 *     Spline* val[12];
 * };
 * }
 */
public class Spline {

    public static MemoryLayout $LAYOUT() {
        return constants$26.const$2;
    }
    public static VarHandle len$VH() {
        return constants$26.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int len;
     * }
     */
    public static int len(MemorySegment seg) {
        return (int)constants$26.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int len;
     * }
     */
    public static void len(MemorySegment seg, int x) {
        constants$26.const$3.set(seg, x);
    }
    public static int lenAtIndex(MemorySegment seg, long index) {
        return (int)constants$26.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void lenAtIndex(MemorySegment seg, long index, int x) {
        constants$26.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle typ$VH() {
        return constants$26.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int typ;
     * }
     */
    public static int typ(MemorySegment seg) {
        return (int)constants$26.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int typ;
     * }
     */
    public static void typ(MemorySegment seg, int x) {
        constants$26.const$4.set(seg, x);
    }
    public static int typAtIndex(MemorySegment seg, long index) {
        return (int)constants$26.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void typAtIndex(MemorySegment seg, long index, int x) {
        constants$26.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment loc(MemorySegment seg) {
        return seg.asSlice(8, 48);
    }
    public static MemorySegment der(MemorySegment seg) {
        return seg.asSlice(56, 48);
    }
    public static MemorySegment val(MemorySegment seg) {
        return seg.asSlice(104, 96);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}