// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SplineStack {
 *     Spline stack[42];
 *     FixSpline fstack[151];
 *     int len;
 *     int flen;
 * };
 * }
 */
public class SplineStack {

    public static MemoryLayout $LAYOUT() {
        return constants$27.const$2;
    }
    public static MemorySegment stack(MemorySegment seg) {
        return seg.asSlice(0, 8400);
    }
    public static MemorySegment fstack(MemorySegment seg) {
        return seg.asSlice(8400, 1208);
    }
    public static VarHandle len$VH() {
        return constants$27.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int len;
     * }
     */
    public static int len(MemorySegment seg) {
        return (int)constants$27.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int len;
     * }
     */
    public static void len(MemorySegment seg, int x) {
        constants$27.const$3.set(seg, x);
    }
    public static int lenAtIndex(MemorySegment seg, long index) {
        return (int)constants$27.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void lenAtIndex(MemorySegment seg, long index, int x) {
        constants$27.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle flen$VH() {
        return constants$27.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int flen;
     * }
     */
    public static int flen(MemorySegment seg) {
        return (int)constants$27.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int flen;
     * }
     */
    public static void flen(MemorySegment seg, int x) {
        constants$27.const$4.set(seg, x);
    }
    public static int flenAtIndex(MemorySegment seg, long index) {
        return (int)constants$27.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void flenAtIndex(MemorySegment seg, long index, int x) {
        constants$27.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}