// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct StrongholdIter {
 *     Pos pos;
 *     Pos nextapprox;
 *     int index;
 *     int ringnum;
 *     int ringmax;
 *     int ringidx;
 *     double angle;
 *     double dist;
 *     uint64_t rnds;
 *     int mc;
 * };
 * }
 */
public class StrongholdIter {

    public static MemoryLayout $LAYOUT() {
        return constants$52.const$5;
    }
    public static MemorySegment pos(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment nextapprox(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static VarHandle index$VH() {
        return constants$53.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int index;
     * }
     */
    public static int index(MemorySegment seg) {
        return (int)constants$53.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int index;
     * }
     */
    public static void index(MemorySegment seg, int x) {
        constants$53.const$0.set(seg, x);
    }
    public static int indexAtIndex(MemorySegment seg, long index) {
        return (int)constants$53.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void indexAtIndex(MemorySegment seg, long index, int x) {
        constants$53.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ringnum$VH() {
        return constants$53.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int ringnum;
     * }
     */
    public static int ringnum(MemorySegment seg) {
        return (int)constants$53.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int ringnum;
     * }
     */
    public static void ringnum(MemorySegment seg, int x) {
        constants$53.const$1.set(seg, x);
    }
    public static int ringnumAtIndex(MemorySegment seg, long index) {
        return (int)constants$53.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void ringnumAtIndex(MemorySegment seg, long index, int x) {
        constants$53.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ringmax$VH() {
        return constants$53.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int ringmax;
     * }
     */
    public static int ringmax(MemorySegment seg) {
        return (int)constants$53.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int ringmax;
     * }
     */
    public static void ringmax(MemorySegment seg, int x) {
        constants$53.const$2.set(seg, x);
    }
    public static int ringmaxAtIndex(MemorySegment seg, long index) {
        return (int)constants$53.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void ringmaxAtIndex(MemorySegment seg, long index, int x) {
        constants$53.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ringidx$VH() {
        return constants$53.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int ringidx;
     * }
     */
    public static int ringidx(MemorySegment seg) {
        return (int)constants$53.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int ringidx;
     * }
     */
    public static void ringidx(MemorySegment seg, int x) {
        constants$53.const$3.set(seg, x);
    }
    public static int ringidxAtIndex(MemorySegment seg, long index) {
        return (int)constants$53.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void ringidxAtIndex(MemorySegment seg, long index, int x) {
        constants$53.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle angle$VH() {
        return constants$53.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double angle;
     * }
     */
    public static double angle(MemorySegment seg) {
        return (double)constants$53.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double angle;
     * }
     */
    public static void angle(MemorySegment seg, double x) {
        constants$53.const$4.set(seg, x);
    }
    public static double angleAtIndex(MemorySegment seg, long index) {
        return (double)constants$53.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void angleAtIndex(MemorySegment seg, long index, double x) {
        constants$53.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dist$VH() {
        return constants$53.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double dist;
     * }
     */
    public static double dist(MemorySegment seg) {
        return (double)constants$53.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double dist;
     * }
     */
    public static void dist(MemorySegment seg, double x) {
        constants$53.const$5.set(seg, x);
    }
    public static double distAtIndex(MemorySegment seg, long index) {
        return (double)constants$53.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void distAtIndex(MemorySegment seg, long index, double x) {
        constants$53.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rnds$VH() {
        return constants$54.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t rnds;
     * }
     */
    public static long rnds(MemorySegment seg) {
        return (long)constants$54.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t rnds;
     * }
     */
    public static void rnds(MemorySegment seg, long x) {
        constants$54.const$0.set(seg, x);
    }
    public static long rndsAtIndex(MemorySegment seg, long index) {
        return (long)constants$54.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void rndsAtIndex(MemorySegment seg, long index, long x) {
        constants$54.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mc$VH() {
        return constants$54.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static int mc(MemorySegment seg) {
        return (int)constants$54.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int mc;
     * }
     */
    public static void mc(MemorySegment seg, int x) {
        constants$54.const$1.set(seg, x);
    }
    public static int mcAtIndex(MemorySegment seg, long index) {
        return (int)constants$54.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void mcAtIndex(MemorySegment seg, long index, int x) {
        constants$54.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}