// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct StructureConfig {
 *     int32_t salt;
 *     int8_t regionSize;
 *     int8_t chunkRange;
 *     uint8_t structType;
 *     int8_t dim;
 *     float rarity;
 * };
 * }
 */
public class StructureConfig {

    public static MemoryLayout $LAYOUT() {
        return constants$48.const$3;
    }
    public static VarHandle salt$VH() {
        return constants$48.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t salt;
     * }
     */
    public static int salt(MemorySegment seg) {
        return (int)constants$48.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t salt;
     * }
     */
    public static void salt(MemorySegment seg, int x) {
        constants$48.const$4.set(seg, x);
    }
    public static int saltAtIndex(MemorySegment seg, long index) {
        return (int)constants$48.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void saltAtIndex(MemorySegment seg, long index, int x) {
        constants$48.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle regionSize$VH() {
        return constants$48.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t regionSize;
     * }
     */
    public static byte regionSize(MemorySegment seg) {
        return (byte)constants$48.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t regionSize;
     * }
     */
    public static void regionSize(MemorySegment seg, byte x) {
        constants$48.const$5.set(seg, x);
    }
    public static byte regionSizeAtIndex(MemorySegment seg, long index) {
        return (byte)constants$48.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void regionSizeAtIndex(MemorySegment seg, long index, byte x) {
        constants$48.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle chunkRange$VH() {
        return constants$49.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t chunkRange;
     * }
     */
    public static byte chunkRange(MemorySegment seg) {
        return (byte)constants$49.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t chunkRange;
     * }
     */
    public static void chunkRange(MemorySegment seg, byte x) {
        constants$49.const$0.set(seg, x);
    }
    public static byte chunkRangeAtIndex(MemorySegment seg, long index) {
        return (byte)constants$49.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void chunkRangeAtIndex(MemorySegment seg, long index, byte x) {
        constants$49.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle structType$VH() {
        return constants$49.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t structType;
     * }
     */
    public static byte structType(MemorySegment seg) {
        return (byte)constants$49.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t structType;
     * }
     */
    public static void structType(MemorySegment seg, byte x) {
        constants$49.const$1.set(seg, x);
    }
    public static byte structTypeAtIndex(MemorySegment seg, long index) {
        return (byte)constants$49.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void structTypeAtIndex(MemorySegment seg, long index, byte x) {
        constants$49.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dim$VH() {
        return constants$49.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t dim;
     * }
     */
    public static byte dim(MemorySegment seg) {
        return (byte)constants$49.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t dim;
     * }
     */
    public static void dim(MemorySegment seg, byte x) {
        constants$49.const$2.set(seg, x);
    }
    public static byte dimAtIndex(MemorySegment seg, long index) {
        return (byte)constants$49.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void dimAtIndex(MemorySegment seg, long index, byte x) {
        constants$49.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rarity$VH() {
        return constants$49.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float rarity;
     * }
     */
    public static float rarity(MemorySegment seg) {
        return (float)constants$49.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float rarity;
     * }
     */
    public static void rarity(MemorySegment seg, float x) {
        constants$49.const$3.set(seg, x);
    }
    public static float rarityAtIndex(MemorySegment seg, long index) {
        return (float)constants$49.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void rarityAtIndex(MemorySegment seg, long index, float x) {
        constants$49.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}