// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct StructureSaltConfig {
 *     int32_t generationStep;
 *     int32_t decoratorIndex;
 * };
 * }
 */
public class StructureSaltConfig {

    public static MemoryLayout $LAYOUT() {
        return constants$49.const$4;
    }
    public static VarHandle generationStep$VH() {
        return constants$49.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t generationStep;
     * }
     */
    public static int generationStep(MemorySegment seg) {
        return (int)constants$49.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t generationStep;
     * }
     */
    public static void generationStep(MemorySegment seg, int x) {
        constants$49.const$5.set(seg, x);
    }
    public static int generationStepAtIndex(MemorySegment seg, long index) {
        return (int)constants$49.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void generationStepAtIndex(MemorySegment seg, long index, int x) {
        constants$49.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle decoratorIndex$VH() {
        return constants$50.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t decoratorIndex;
     * }
     */
    public static int decoratorIndex(MemorySegment seg) {
        return (int)constants$50.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t decoratorIndex;
     * }
     */
    public static void decoratorIndex(MemorySegment seg, int x) {
        constants$50.const$0.set(seg, x);
    }
    public static int decoratorIndexAtIndex(MemorySegment seg, long index) {
        return (int)constants$50.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void decoratorIndexAtIndex(MemorySegment seg, long index, int x) {
        constants$50.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}