// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct StructureVariant {
 *     uint8_t abandoned;
 *     uint8_t giant;
 *     uint8_t underground;
 *     uint8_t airpocket;
 *     uint8_t basement;
 *     uint8_t cracked;
 *     uint8_t size;
 *     uint8_t start;
 *     short biome;
 *     uint8_t rotation;
 *     uint8_t mirror;
 *     int16_t x;
 *     int16_t y;
 *     int16_t z;
 *     int16_t sx;
 *     int16_t sy;
 *     int16_t sz;
 * };
 * }
 */
public class StructureVariant {

    public static MemoryLayout $LAYOUT() {
        return constants$54.const$2;
    }
    public static VarHandle abandoned$VH() {
        return constants$54.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t abandoned;
     * }
     */
    public static byte abandoned(MemorySegment seg) {
        return (byte)constants$54.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t abandoned;
     * }
     */
    public static void abandoned(MemorySegment seg, byte x) {
        constants$54.const$3.set(seg, x);
    }
    public static byte abandonedAtIndex(MemorySegment seg, long index) {
        return (byte)constants$54.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void abandonedAtIndex(MemorySegment seg, long index, byte x) {
        constants$54.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle giant$VH() {
        return constants$54.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t giant;
     * }
     */
    public static byte giant(MemorySegment seg) {
        return (byte)constants$54.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t giant;
     * }
     */
    public static void giant(MemorySegment seg, byte x) {
        constants$54.const$4.set(seg, x);
    }
    public static byte giantAtIndex(MemorySegment seg, long index) {
        return (byte)constants$54.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void giantAtIndex(MemorySegment seg, long index, byte x) {
        constants$54.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle underground$VH() {
        return constants$54.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t underground;
     * }
     */
    public static byte underground(MemorySegment seg) {
        return (byte)constants$54.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t underground;
     * }
     */
    public static void underground(MemorySegment seg, byte x) {
        constants$54.const$5.set(seg, x);
    }
    public static byte undergroundAtIndex(MemorySegment seg, long index) {
        return (byte)constants$54.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void undergroundAtIndex(MemorySegment seg, long index, byte x) {
        constants$54.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle airpocket$VH() {
        return constants$55.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t airpocket;
     * }
     */
    public static byte airpocket(MemorySegment seg) {
        return (byte)constants$55.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t airpocket;
     * }
     */
    public static void airpocket(MemorySegment seg, byte x) {
        constants$55.const$0.set(seg, x);
    }
    public static byte airpocketAtIndex(MemorySegment seg, long index) {
        return (byte)constants$55.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void airpocketAtIndex(MemorySegment seg, long index, byte x) {
        constants$55.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle basement$VH() {
        return constants$55.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t basement;
     * }
     */
    public static byte basement(MemorySegment seg) {
        return (byte)constants$55.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t basement;
     * }
     */
    public static void basement(MemorySegment seg, byte x) {
        constants$55.const$1.set(seg, x);
    }
    public static byte basementAtIndex(MemorySegment seg, long index) {
        return (byte)constants$55.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void basementAtIndex(MemorySegment seg, long index, byte x) {
        constants$55.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle cracked$VH() {
        return constants$55.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t cracked;
     * }
     */
    public static byte cracked(MemorySegment seg) {
        return (byte)constants$55.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t cracked;
     * }
     */
    public static void cracked(MemorySegment seg, byte x) {
        constants$55.const$2.set(seg, x);
    }
    public static byte crackedAtIndex(MemorySegment seg, long index) {
        return (byte)constants$55.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void crackedAtIndex(MemorySegment seg, long index, byte x) {
        constants$55.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle size$VH() {
        return constants$55.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t size;
     * }
     */
    public static byte size(MemorySegment seg) {
        return (byte)constants$55.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t size;
     * }
     */
    public static void size(MemorySegment seg, byte x) {
        constants$55.const$3.set(seg, x);
    }
    public static byte sizeAtIndex(MemorySegment seg, long index) {
        return (byte)constants$55.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void sizeAtIndex(MemorySegment seg, long index, byte x) {
        constants$55.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle start$VH() {
        return constants$55.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t start;
     * }
     */
    public static byte start(MemorySegment seg) {
        return (byte)constants$55.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t start;
     * }
     */
    public static void start(MemorySegment seg, byte x) {
        constants$55.const$4.set(seg, x);
    }
    public static byte startAtIndex(MemorySegment seg, long index) {
        return (byte)constants$55.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void startAtIndex(MemorySegment seg, long index, byte x) {
        constants$55.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle biome$VH() {
        return constants$55.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short biome;
     * }
     */
    public static short biome(MemorySegment seg) {
        return (short)constants$55.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short biome;
     * }
     */
    public static void biome(MemorySegment seg, short x) {
        constants$55.const$5.set(seg, x);
    }
    public static short biomeAtIndex(MemorySegment seg, long index) {
        return (short)constants$55.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void biomeAtIndex(MemorySegment seg, long index, short x) {
        constants$55.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rotation$VH() {
        return constants$56.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t rotation;
     * }
     */
    public static byte rotation(MemorySegment seg) {
        return (byte)constants$56.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t rotation;
     * }
     */
    public static void rotation(MemorySegment seg, byte x) {
        constants$56.const$0.set(seg, x);
    }
    public static byte rotationAtIndex(MemorySegment seg, long index) {
        return (byte)constants$56.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void rotationAtIndex(MemorySegment seg, long index, byte x) {
        constants$56.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mirror$VH() {
        return constants$56.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t mirror;
     * }
     */
    public static byte mirror(MemorySegment seg) {
        return (byte)constants$56.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t mirror;
     * }
     */
    public static void mirror(MemorySegment seg, byte x) {
        constants$56.const$1.set(seg, x);
    }
    public static byte mirrorAtIndex(MemorySegment seg, long index) {
        return (byte)constants$56.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void mirrorAtIndex(MemorySegment seg, long index, byte x) {
        constants$56.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle x$VH() {
        return constants$56.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int16_t x;
     * }
     */
    public static short x(MemorySegment seg) {
        return (short)constants$56.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int16_t x;
     * }
     */
    public static void x(MemorySegment seg, short x) {
        constants$56.const$2.set(seg, x);
    }
    public static short xAtIndex(MemorySegment seg, long index) {
        return (short)constants$56.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void xAtIndex(MemorySegment seg, long index, short x) {
        constants$56.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle y$VH() {
        return constants$56.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int16_t y;
     * }
     */
    public static short y(MemorySegment seg) {
        return (short)constants$56.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int16_t y;
     * }
     */
    public static void y(MemorySegment seg, short x) {
        constants$56.const$3.set(seg, x);
    }
    public static short yAtIndex(MemorySegment seg, long index) {
        return (short)constants$56.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void yAtIndex(MemorySegment seg, long index, short x) {
        constants$56.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle z$VH() {
        return constants$56.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int16_t z;
     * }
     */
    public static short z(MemorySegment seg) {
        return (short)constants$56.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int16_t z;
     * }
     */
    public static void z(MemorySegment seg, short x) {
        constants$56.const$4.set(seg, x);
    }
    public static short zAtIndex(MemorySegment seg, long index) {
        return (short)constants$56.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void zAtIndex(MemorySegment seg, long index, short x) {
        constants$56.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sx$VH() {
        return constants$56.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int16_t sx;
     * }
     */
    public static short sx(MemorySegment seg) {
        return (short)constants$56.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int16_t sx;
     * }
     */
    public static void sx(MemorySegment seg, short x) {
        constants$56.const$5.set(seg, x);
    }
    public static short sxAtIndex(MemorySegment seg, long index) {
        return (short)constants$56.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void sxAtIndex(MemorySegment seg, long index, short x) {
        constants$56.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sy$VH() {
        return constants$57.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int16_t sy;
     * }
     */
    public static short sy(MemorySegment seg) {
        return (short)constants$57.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int16_t sy;
     * }
     */
    public static void sy(MemorySegment seg, short x) {
        constants$57.const$0.set(seg, x);
    }
    public static short syAtIndex(MemorySegment seg, long index) {
        return (short)constants$57.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void syAtIndex(MemorySegment seg, long index, short x) {
        constants$57.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sz$VH() {
        return constants$57.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int16_t sz;
     * }
     */
    public static short sz(MemorySegment seg) {
        return (short)constants$57.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int16_t sz;
     * }
     */
    public static void sz(MemorySegment seg, short x) {
        constants$57.const$1.set(seg, x);
    }
    public static short szAtIndex(MemorySegment seg, long index) {
        return (short)constants$57.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void szAtIndex(MemorySegment seg, long index, short x) {
        constants$57.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}