// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SurfaceNoiseBeta {
 *     OctaveNoise octmin;
 *     OctaveNoise octmax;
 *     OctaveNoise octmain;
 *     OctaveNoise octcontA;
 *     OctaveNoise octcontB;
 *     PerlinNoise oct[66];
 * };
 * }
 */
public class SurfaceNoiseBeta {

    public static MemoryLayout $LAYOUT() {
        return constants$25.const$4;
    }
    public static MemorySegment octmin(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    public static MemorySegment octmax(MemorySegment seg) {
        return seg.asSlice(16, 16);
    }
    public static MemorySegment octmain(MemorySegment seg) {
        return seg.asSlice(32, 16);
    }
    public static MemorySegment octcontA(MemorySegment seg) {
        return seg.asSlice(48, 16);
    }
    public static MemorySegment octcontB(MemorySegment seg) {
        return seg.asSlice(64, 16);
    }
    public static MemorySegment oct(MemorySegment seg) {
        return seg.asSlice(80, 21120);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}