// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SurfaceNoise {
 *     double xzScale;
 *     double yScale;
 *     double xzFactor;
 *     double yFactor;
 *     OctaveNoise octmin;
 *     OctaveNoise octmax;
 *     OctaveNoise octmain;
 *     OctaveNoise octsurf;
 *     OctaveNoise octdepth;
 *     PerlinNoise oct[60];
 * };
 * }
 */
public class SurfaceNoise {

    public static MemoryLayout $LAYOUT() {
        return constants$24.const$5;
    }
    public static VarHandle xzScale$VH() {
        return constants$25.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double xzScale;
     * }
     */
    public static double xzScale(MemorySegment seg) {
        return (double)constants$25.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double xzScale;
     * }
     */
    public static void xzScale(MemorySegment seg, double x) {
        constants$25.const$0.set(seg, x);
    }
    public static double xzScaleAtIndex(MemorySegment seg, long index) {
        return (double)constants$25.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void xzScaleAtIndex(MemorySegment seg, long index, double x) {
        constants$25.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle yScale$VH() {
        return constants$25.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double yScale;
     * }
     */
    public static double yScale(MemorySegment seg) {
        return (double)constants$25.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double yScale;
     * }
     */
    public static void yScale(MemorySegment seg, double x) {
        constants$25.const$1.set(seg, x);
    }
    public static double yScaleAtIndex(MemorySegment seg, long index) {
        return (double)constants$25.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void yScaleAtIndex(MemorySegment seg, long index, double x) {
        constants$25.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle xzFactor$VH() {
        return constants$25.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double xzFactor;
     * }
     */
    public static double xzFactor(MemorySegment seg) {
        return (double)constants$25.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double xzFactor;
     * }
     */
    public static void xzFactor(MemorySegment seg, double x) {
        constants$25.const$2.set(seg, x);
    }
    public static double xzFactorAtIndex(MemorySegment seg, long index) {
        return (double)constants$25.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void xzFactorAtIndex(MemorySegment seg, long index, double x) {
        constants$25.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle yFactor$VH() {
        return constants$25.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double yFactor;
     * }
     */
    public static double yFactor(MemorySegment seg) {
        return (double)constants$25.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double yFactor;
     * }
     */
    public static void yFactor(MemorySegment seg, double x) {
        constants$25.const$3.set(seg, x);
    }
    public static double yFactorAtIndex(MemorySegment seg, long index) {
        return (double)constants$25.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void yFactorAtIndex(MemorySegment seg, long index, double x) {
        constants$25.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment octmin(MemorySegment seg) {
        return seg.asSlice(32, 16);
    }
    public static MemorySegment octmax(MemorySegment seg) {
        return seg.asSlice(48, 16);
    }
    public static MemorySegment octmain(MemorySegment seg) {
        return seg.asSlice(64, 16);
    }
    public static MemorySegment octsurf(MemorySegment seg) {
        return seg.asSlice(80, 16);
    }
    public static MemorySegment octdepth(MemorySegment seg) {
        return seg.asSlice(96, 16);
    }
    public static MemorySegment oct(MemorySegment seg) {
        return seg.asSlice(112, 19200);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}