// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct TerrainNoiseParameters {
 *     BiomeNoise bn;
 *     BlendedNoise bln;
 *     SplineStack ss;
 *     Spline* factorSpline;
 *     Spline* jaggednessSpline;
 *     PerlinNoise oct[90];
 *     DoublePerlinNoise pillar;
 *     DoublePerlinNoise pillarRareness;
 *     DoublePerlinNoise pillarThickness;
 *     DoublePerlinNoise spaghetti2d;
 *     DoublePerlinNoise spaghetti2dElevation;
 *     DoublePerlinNoise spaghetti2dModulator;
 *     DoublePerlinNoise spaghetti2dThickness;
 *     DoublePerlinNoise spaghetti3d1;
 *     DoublePerlinNoise spaghetti3d2;
 *     DoublePerlinNoise spaghetti3dRarity;
 *     DoublePerlinNoise spaghetti3dThickness;
 *     DoublePerlinNoise spaghettiRoughness;
 *     DoublePerlinNoise spaghettiRoughnessModulator;
 *     DoublePerlinNoise caveEntrance;
 *     DoublePerlinNoise caveLayer;
 *     DoublePerlinNoise caveCheese;
 *     DoublePerlinNoise noodle;
 *     DoublePerlinNoise noodleThickness;
 *     DoublePerlinNoise noodleRidgeA;
 *     DoublePerlinNoise noodleRidgeB;
 *     DoublePerlinNoise jagged;
 * };
 * }
 */
public class TerrainNoiseParameters {

    public static MemoryLayout $LAYOUT() {
        return constants$31.const$4;
    }
    public static MemorySegment bn(MemorySegment seg) {
        return seg.asSlice(0, 24592);
    }
    public static MemorySegment bln(MemorySegment seg) {
        return seg.asSlice(24592, 12920);
    }
    public static MemorySegment ss(MemorySegment seg) {
        return seg.asSlice(37512, 9616);
    }
    public static VarHandle factorSpline$VH() {
        return constants$31.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Spline* factorSpline;
     * }
     */
    public static MemorySegment factorSpline(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$31.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Spline* factorSpline;
     * }
     */
    public static void factorSpline(MemorySegment seg, MemorySegment x) {
        constants$31.const$5.set(seg, x);
    }
    public static MemorySegment factorSplineAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$31.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void factorSplineAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$31.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle jaggednessSpline$VH() {
        return constants$32.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Spline* jaggednessSpline;
     * }
     */
    public static MemorySegment jaggednessSpline(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$32.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Spline* jaggednessSpline;
     * }
     */
    public static void jaggednessSpline(MemorySegment seg, MemorySegment x) {
        constants$32.const$0.set(seg, x);
    }
    public static MemorySegment jaggednessSplineAtIndex(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$32.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void jaggednessSplineAtIndex(MemorySegment seg, long index, MemorySegment x) {
        constants$32.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment oct(MemorySegment seg) {
        return seg.asSlice(47144, 28800);
    }
    public static MemorySegment pillar(MemorySegment seg) {
        return seg.asSlice(75944, 40);
    }
    public static MemorySegment pillarRareness(MemorySegment seg) {
        return seg.asSlice(75984, 40);
    }
    public static MemorySegment pillarThickness(MemorySegment seg) {
        return seg.asSlice(76024, 40);
    }
    public static MemorySegment spaghetti2d(MemorySegment seg) {
        return seg.asSlice(76064, 40);
    }
    public static MemorySegment spaghetti2dElevation(MemorySegment seg) {
        return seg.asSlice(76104, 40);
    }
    public static MemorySegment spaghetti2dModulator(MemorySegment seg) {
        return seg.asSlice(76144, 40);
    }
    public static MemorySegment spaghetti2dThickness(MemorySegment seg) {
        return seg.asSlice(76184, 40);
    }
    public static MemorySegment spaghetti3d1(MemorySegment seg) {
        return seg.asSlice(76224, 40);
    }
    public static MemorySegment spaghetti3d2(MemorySegment seg) {
        return seg.asSlice(76264, 40);
    }
    public static MemorySegment spaghetti3dRarity(MemorySegment seg) {
        return seg.asSlice(76304, 40);
    }
    public static MemorySegment spaghetti3dThickness(MemorySegment seg) {
        return seg.asSlice(76344, 40);
    }
    public static MemorySegment spaghettiRoughness(MemorySegment seg) {
        return seg.asSlice(76384, 40);
    }
    public static MemorySegment spaghettiRoughnessModulator(MemorySegment seg) {
        return seg.asSlice(76424, 40);
    }
    public static MemorySegment caveEntrance(MemorySegment seg) {
        return seg.asSlice(76464, 40);
    }
    public static MemorySegment caveLayer(MemorySegment seg) {
        return seg.asSlice(76504, 40);
    }
    public static MemorySegment caveCheese(MemorySegment seg) {
        return seg.asSlice(76544, 40);
    }
    public static MemorySegment noodle(MemorySegment seg) {
        return seg.asSlice(76584, 40);
    }
    public static MemorySegment noodleThickness(MemorySegment seg) {
        return seg.asSlice(76624, 40);
    }
    public static MemorySegment noodleRidgeA(MemorySegment seg) {
        return seg.asSlice(76664, 40);
    }
    public static MemorySegment noodleRidgeB(MemorySegment seg) {
        return seg.asSlice(76704, 40);
    }
    public static MemorySegment jagged(MemorySegment seg) {
        return seg.asSlice(76744, 40);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}