// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Xoroshiro {
 *     uint64_t lo;
 *     uint64_t hi;
 * };
 * }
 */
public class Xoroshiro {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$0;
    }
    public static VarHandle lo$VH() {
        return constants$0.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t lo;
     * }
     */
    public static long lo(MemorySegment seg) {
        return (long)constants$0.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t lo;
     * }
     */
    public static void lo(MemorySegment seg, long x) {
        constants$0.const$1.set(seg, x);
    }
    public static long loAtIndex(MemorySegment seg, long index) {
        return (long)constants$0.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void loAtIndex(MemorySegment seg, long index, long x) {
        constants$0.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hi$VH() {
        return constants$0.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t hi;
     * }
     */
    public static long hi(MemorySegment seg) {
        return (long)constants$0.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t hi;
     * }
     */
    public static void hi(MemorySegment seg, long x) {
        constants$0.const$2.set(seg, x);
    }
    public static long hiAtIndex(MemorySegment seg, long index) {
        return (long)constants$0.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void hiAtIndex(MemorySegment seg, long index, long x) {
        constants$0.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    public static MemorySegment asSlice(MemorySegment seg, long index) {
        return seg.asSlice(index*sizeof(), sizeof());
    }

}